import { authTables } from '@convex-dev/auth/server'
import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'
export const SHOP_CATEGORIES = ['Medicines (Branded)','Generic Medicines','Mankind Products',"Dr. Reddy's Products",'Apollo Products','Cipla Products','Sun Pharma Products','Abbott Products','Lupin Products','Himalaya Products','Torrent Products','Pfizer Products','Glenmark Products','Zydus Products','Pet Care','Grocery / Health Supplements','Baby Care','Personal Care'] as const
export default defineSchema({
 ...authTables,
 users: defineTable({ name:v.optional(v.string()),image:v.optional(v.string()),email:v.optional(v.string()),emailVerificationTime:v.optional(v.number()),phone:v.optional(v.string()),phoneVerificationTime:v.optional(v.number()),isAnonymous:v.optional(v.boolean()),googleSubject:v.optional(v.string()),authTokenIdentifier:v.optional(v.string()),dateOfBirth:v.optional(v.string()),gender:v.optional(v.string()),addressLine:v.optional(v.string()),landmark:v.optional(v.string()),city:v.optional(v.string()),state:v.optional(v.string()),pincode:v.optional(v.string()),avatarKey:v.optional(v.string()),emergencyContact:v.optional(v.string()) }).index('email',['email']).index('google_subject',['googleSubject']).index('by_auth_token',['authTokenIdentifier']).index('phone',['phone']),
 loginEvents: defineTable({userId:v.id('users'),email:v.string(),time:v.number()}).index('by_user',['userId']).index('by_email',['email']).index('by_time',['time']),
 productViews: defineTable({userId:v.id('users'),email:v.string(),medicineId:v.id('medicines'),medicineName:v.string(),time:v.number()}).index('by_user',['userId']).index('by_email',['email']).index('by_time',['time']),
 adminNotifications: defineTable({message:v.string(),time:v.number(),read:v.boolean()}).index('by_time',['time']),
 imageRegistry: defineTable({medicineId:v.id('medicines'),medicineName:v.string(),imageUrl:v.string(),source:v.string(),verifiedAt:v.number(),status:v.union(v.literal('verified'),v.literal('revoked'))}).index('by_medicine',['medicineId']).index('by_name',['medicineName']),
 medicines: defineTable({name:v.string(),manufacturer:v.optional(v.string()),category:v.string(),description:v.string(),price:v.number(),mrpPrice:v.optional(v.number()),stock:v.number(),requiresPrescription:v.boolean(),imageUrl:v.optional(v.string()),active:v.boolean(),shopCategory:v.optional(v.string()),featured:v.optional(v.boolean()),updatedAt:v.optional(v.number()),tabletsPerPack:v.optional(v.number()),barcode:v.optional(v.string()),reorderLevel:v.optional(v.number()),expiryDate:v.optional(v.string()),batchNumber:v.optional(v.string())}).index('by_active',['active']).index('by_category',['category']).index('by_name',['name']).index('by_shop_category',['shopCategory']).index('by_barcode',['barcode']).searchIndex('search_name',{searchField:'name',filterFields:['active','shopCategory','category']}),
 shops: defineTable({name:v.string(),address:v.string(),active:v.boolean(),staffNames:v.array(v.string()),createdAt:v.number()}).index('by_active',['active']),
 shopSales: defineTable({shopId:v.id('shops'),medicineId:v.id('medicines'),medicineName:v.string(),quantityTablets:v.number(),tabletsPerPack:v.number(),packPrice:v.number(),unitPrice:v.number(),lineTotal:v.number(),staffName:v.string(),paymentMethod:v.union(v.literal('cash'),v.literal('upi'),v.literal('card'),v.literal('other')),soldAt:v.number(),saleDay:v.string()}).index('by_shop_day',['shopId','saleDay']).index('by_day',['saleDay']),
 coupons: defineTable({code:v.string(),type:v.union(v.literal('flat'),v.literal('percent')),value:v.number(),minOrder:v.number(),maxOff:v.optional(v.number()),active:v.boolean()}).index('by_code',['code']),
 settings: defineTable({key:v.string(),storeName:v.optional(v.string()),address:v.optional(v.string()),phone:v.optional(v.string()),hours:v.optional(v.string())}).index('by_key',['key']),
 orders: defineTable({customerName:v.string(),customerPhone:v.string(),customerEmail:v.optional(v.string()),fulfillment:v.union(v.literal('pickup'),v.literal('delivery')),deliveryAddress:v.optional(v.string()),deliveryTimePref:v.optional(v.string()),paymentMethod:v.union(v.literal('cash'),v.literal('online'),v.literal('upi'),v.literal('card'),v.literal('cod'),v.literal('wallet')),paymentStatus:v.union(v.literal('pending'),v.literal('paid'),v.literal('cash_on_fulfillment')),status:v.union(v.literal('placed'),v.literal('preparing'),v.literal('ready_or_out'),v.literal('completed'),v.literal('cancelled')),items:v.array(v.object({medicineId:v.id('medicines'),name:v.string(),price:v.number(),mrpPrice:v.optional(v.number()),quantity:v.number()})),subtotal:v.optional(v.number()),discount:v.optional(v.number()),couponCode:v.optional(v.string()),deliveryCharge:v.optional(v.number()),total:v.number(),notes:v.optional(v.string())}).index('by_status',['status']).index('by_fulfillment',['fulfillment']).index('by_phone',['customerPhone']).index('by_email',['customerEmail']),
 staff: defineTable({email:v.string(),name:v.string(),role:v.union(v.literal('admin'),v.literal('manager'),v.literal('billing'),v.literal('inventory'),v.literal('staff')),active:v.boolean(),permissions:v.array(v.string()),shopId:v.optional(v.id('shops')),maxDiscountPercent:v.number(),createdAt:v.number(),updatedAt:v.number()}).index('by_email',['email']).index('by_active',['active']),
 staffRequests: defineTable({email:v.string(),name:v.string(),status:v.union(v.literal('pending'),v.literal('approved'),v.literal('rejected')),createdAt:v.number(),updatedAt:v.number(),reviewedBy:v.optional(v.string())}).index('by_email',['email']).index('by_status',['status']),
 staffShifts: defineTable({staffId:v.id('staff'),staffName:v.string(),shopId:v.optional(v.id('shops')),startedAt:v.number(),endedAt:v.optional(v.number()),openingCash:v.number(),expectedCash:v.number(),actualCash:v.optional(v.number()),difference:v.optional(v.number()),status:v.union(v.literal('open'),v.literal('closed'))}).index('by_staff',['staffId']).index('by_status',['status']).index('by_started',['startedAt']),
 staffSales: defineTable({staffId:v.id('staff'),staffName:v.string(),shiftId:v.id('staffShifts'),customerName:v.optional(v.string()),customerPhone:v.optional(v.string()),items:v.array(v.object({medicineId:v.id('medicines'),name:v.string(),quantity:v.number(),price:v.number(),total:v.number()})),subtotal:v.number(),discount:v.number(),total:v.number(),paymentMethod:v.union(v.literal('cash'),v.literal('upi'),v.literal('card'),v.literal('other')),status:v.union(v.literal('completed'),v.literal('cancelled')),createdAt:v.number(),invoiceNo:v.optional(v.string())}).index('by_shift',['shiftId']).index('by_staff',['staffId']).index('by_created',['createdAt']),
 stockMovements: defineTable({staffId:v.id('staff'),staffName:v.string(),medicineId:v.id('medicines'),medicineName:v.string(),type:v.union(v.literal('purchase'),v.literal('adjustment'),v.literal('damage'),v.literal('expired'),v.literal('return'),v.literal('sale')),quantity:v.number(),beforeStock:v.number(),afterStock:v.number(),reason:v.optional(v.string()),createdAt:v.number()}).index('by_medicine',['medicineId']).index('by_staff',['staffId']).index('by_created',['createdAt']),
 staffReturns: defineTable({staffId:v.id('staff'),staffName:v.string(),saleId:v.optional(v.id('staffSales')),orderId:v.optional(v.id('orders')),medicineId:v.id('medicines'),medicineName:v.string(),quantity:v.number(),reason:v.string(),disposition:v.union(v.literal('resellable'),v.literal('damaged'),v.literal('expired')),refundAmount:v.number(),createdAt:v.number()}).index('by_staff',['staffId']).index('by_created',['createdAt']),
 staffTasks: defineTable({title:v.string(),description:v.optional(v.string()),assignedStaffId:v.optional(v.id('staff')),assignedStaffName:v.optional(v.string()),status:v.union(v.literal('pending'),v.literal('in_progress'),v.literal('completed')),createdAt:v.number(),completedAt:v.optional(v.number())}).index('by_staff',['assignedStaffId']).index('by_status',['status']),
 auditLogs: defineTable({staffId:v.optional(v.id('staff')),staffName:v.string(),action:v.string(),entityType:v.string(),entityId:v.optional(v.string()),details:v.string(),createdAt:v.number()}).index('by_staff',['staffId']).index('by_created',['createdAt']),
 customers: defineTable({name:v.string(),phone:v.string(),email:v.optional(v.string()),address:v.optional(v.string()),notes:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number()}).index('by_phone',['phone']),
 prescriptions: defineTable({customerName:v.string(),customerPhone:v.string(),imageUrl:v.optional(v.string()),notes:v.optional(v.string()),status:v.union(v.literal('pending'),v.literal('approved'),v.literal('rejected')),verifiedBy:v.optional(v.string()),rejectionReason:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number()}).index('by_status',['status']).index('by_phone',['customerPhone']),
})