import { query, mutation } from './_generated/server'
import { v } from 'convex/values'
import type { Id } from './_generated/dataModel'
import { getAppUserId } from './appAuth'
const ADMIN_EMAIL='adnayyar786@gmail.com'
const ok=(data:any)=>({ok:true as const,...data}), fail=(code:string,message:string)=>({ok:false as const,code,message})
async function current(ctx:any){
  const uid=await getAppUserId(ctx)
  if(!uid)return null
  const user=await ctx.db.get(uid)
  const email=user?.email?.trim().toLowerCase()
  if(!email || email===ADMIN_EMAIL)return null
  const staff=await ctx.db.query('staff').withIndex('by_email',q=>q.eq('email',email)).first()
  return staff&&staff.active?staff:null
}
async function requireAdmin(ctx:any){const identity=await ctx.auth.getUserIdentity();const email=typeof identity?.email==='string'?identity.email.trim().toLowerCase():'';if(email!==ADMIN_EMAIL)throw new Error('Only the Wellcare Medicose admin can manage staff access.');return email}
const STAFF_PERMISSIONS=['dashboard','billing','orders','medicines_view','stock_view','customers','prescriptions','expiry','cash_shift','reports','tasks','returns','stock_adjust'] as const
export const isAdmin=query({args:{},handler:async(ctx)=>{const identity=await ctx.auth.getUserIdentity();const email=typeof identity?.email==='string'?identity.email.trim().toLowerCase():'';return email===ADMIN_EMAIL?{email}:null}})
export const accessStatus=query({args:{email:v.string()},handler:async(ctx,args)=>{const email=args.email.trim().toLowerCase();if(!email||email===ADMIN_EMAIL)return {status:'not_allowed' as const};const staff=await ctx.db.query('staff').withIndex('by_email',q=>q.eq('email',email)).first();if(staff)return {status:staff.active?'approved' as const:'pending' as const};const request=await ctx.db.query('staffRequests').withIndex('by_email',q=>q.eq('email',email)).first();return {status:request?.status==='pending'?'pending' as const:request?.status==='rejected'?'rejected' as const:'not_requested' as const}}})
export const requestAccess=mutation({args:{email:v.string(),name:v.string()},handler:async(ctx,args)=>{const email=args.email.trim().toLowerCase(),name=args.name.trim();if(!email||!name)throw new Error('Name and Gmail are required.');if(email===ADMIN_EMAIL)throw new Error('This Gmail is reserved for the admin.');const existing=await ctx.db.query('staff').withIndex('by_email',q=>q.eq('email',email)).first();if(existing&&existing.active)return {status:'approved' as const};const old=await ctx.db.query('staffRequests').withIndex('by_email',q=>q.eq('email',email)).first();if(old){await ctx.db.patch(old._id,{name,status:'pending',updatedAt:Date.now()});return {status:'pending' as const}}await ctx.db.insert('staffRequests',{email,name,status:'pending',createdAt:Date.now(),updatedAt:Date.now()});return {status:'pending' as const}})
export const listRequests=query({args:{},handler:async(ctx)=>{await requireAdmin(ctx);return await ctx.db.query('staffRequests').withIndex('by_status',q=>q.eq('status','pending')).order('desc').collect()}})
export const listAllStaff=query({args:{},handler:async(ctx)=>{await requireAdmin(ctx);return await ctx.db.query('staff').order('desc').collect()}})
export const adminAddStaff=mutation({args:{email:v.string(),name:v.string(),role:v.union(v.literal('manager'),v.literal('billing'),v.literal('inventory'),v.literal('staff'))},handler:async(ctx,args)=>{await requireAdmin(ctx);const email=args.email.trim().toLowerCase(),name=args.name.trim();if(!email||!name)throw new Error('Name and Gmail are required.');if(email===ADMIN_EMAIL)throw new Error('The admin Gmail cannot be added as staff.');const existing=await ctx.db.query('staff').withIndex('by_email',q=>q.eq('email',email)).first();const data={email,name,role:args.role,active:true,permissions:[...STAFF_PERMISSIONS],maxDiscountPercent:5,updatedAt:Date.now()};if(existing){await ctx.db.patch(existing._id,data);return existing._id}return await ctx.db.insert('staff',{...data,createdAt:Date.now()})}})
export const approveRequest=mutation({args:{id:v.id('staffRequests'),role:v.union(v.literal('manager'),v.literal('billing'),v.literal('inventory'),v.literal('staff'))},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx);const req=await ctx.db.get(args.id);if(!req||req.status!=='pending')throw new Error('Staff request is no longer pending.');const existing=await ctx.db.query('staff').withIndex('by_email',q=>q.eq('email',req.email)).first();if(existing)await ctx.db.patch(existing._id,{name:req.name,role:args.role,active:true,permissions:[...STAFF_PERMISSIONS],updatedAt:Date.now()});else await ctx.db.insert('staff',{email:req.email,name:req.name,role:args.role,active:true,permissions:[...STAFF_PERMISSIONS],maxDiscountPercent:5,createdAt:Date.now(),updatedAt:Date.now()});await ctx.db.patch(req._id,{status:'approved',updatedAt:Date.now(),reviewedBy:admin});return {ok:true as const}})
export const rejectRequest=mutation({args:{id:v.id('staffRequests')},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx);const req=await ctx.db.get(args.id);if(!req)throw new Error('Staff request not found.');await ctx.db.patch(req._id,{status:'rejected',updatedAt:Date.now(),reviewedBy:admin});return {ok:true as const}})
export const setActive=mutation({args:{id:v.id('staff'),active:v.boolean()},handler:async(ctx,args)=>{await requireAdmin(ctx);const staff=await ctx.db.get(args.id);if(!staff)throw new Error('Staff account not found.');await ctx.db.patch(staff._id,{active:args.active,updatedAt:Date.now()});return {ok:true as const}}})
function can(s:any,p:string){return s.role==='admin'||s.role==='manager'||s.permissions.includes(p)}
export const me=query({args:{},handler:async(ctx)=>await current(ctx)})
export const dashboard=query({args:{},handler:async(ctx)=>{const s=await current(ctx);if(!s)return fail('FORBIDDEN','Staff access required');const meds=await ctx.db.query('medicines').withIndex('by_active',q=>q.eq('active',true)).collect();const orders=await ctx.db.query('orders').order('desc').take(100);const today=new Date().toISOString().slice(0,10);const sales=await ctx.db.query('staffSales').order('desc').take(300);const todaySales=sales.filter(x=>new Date(x.createdAt).toISOString().slice(0,10)===today&&x.status==='completed');const now=Date.now(), soon=now+30*86400000;const exp=meds.filter(m=>m.expiryDate&&new Date(m.expiryDate).getTime()<=soon).length;const shift=await ctx.db.query('staffShifts').withIndex('by_staff',q=>q.eq('staffId',s._id)).order('desc').first();return ok({staff:s,counts:{low:meds.filter(m=>m.stock>0&&m.stock<=(m.reorderLevel??10)).length,out:meds.filter(m=>m.stock<=0).length,expiry:exp,pendingOrders:orders.filter(o=>o.status==='placed').length,rx:orders.filter(o=>o.items.some(i=>meds.some(m=>String(m._id)===String(i.medicineId)&&m.requiresPrescription))).length},todayTotal:todaySales.reduce((n,x)=>n+x.total,0),todayBills:todaySales.length,shift})}})
export const medicines=query({args:{search:v.optional(v.string())},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'medicines_view'))return [];const all=await ctx.db.query('medicines').withIndex('by_active',q=>q.eq('active',true)).collect();const term=args.search?.trim().toLowerCase();return(term?all.filter(m=>m.name.toLowerCase().includes(term)||m.category.toLowerCase().includes(term)||(m.barcode??'').toLowerCase().includes(term)):all).slice(0,100)}})
export const orders=query({args:{},handler:async(ctx)=>{const s=await current(ctx);if(!s||!can(s,'orders'))return [];return await ctx.db.query('orders').order('desc').take(100)}})
export const customers=query({args:{phone:v.optional(v.string())},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'customers'))return [];if(args.phone?.trim()){const c=await ctx.db.query('customers').withIndex('by_phone',q=>q.eq('phone',args.phone!.trim())).first();return c?[c]:[]}return await ctx.db.query('customers').order('desc').take(50)}})
export const saveCustomer=mutation({args:{name:v.string(),phone:v.string(),email:v.optional(v.string()),address:v.optional(v.string()),notes:v.optional(v.string())},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'customers'))return fail('FORBIDDEN','Customer access is not allowed');const phone=args.phone.trim();if(!phone)return fail('PHONE','Phone is required');const old=await ctx.db.query('customers').withIndex('by_phone',q=>q.eq('phone',phone)).first();const data={name:args.name.trim(),phone,email:args.email?.trim()||undefined,address:args.address?.trim()||undefined,notes:args.notes?.trim()||undefined,updatedAt:Date.now()};if(old){await ctx.db.patch(old._id,data);return ok({id:old._id})}const id=await ctx.db.insert('customers',{...data,createdAt:Date.now()});return ok({id})}})
export const prescriptions=query({args:{status:v.optional(v.union(v.literal('pending'),v.literal('approved'),v.literal('rejected')))},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'prescriptions'))return [];return args.status?await ctx.db.query('prescriptions').withIndex('by_status',q=>q.eq('status',args.status!)).order('desc').take(100):await ctx.db.query('prescriptions').order('desc').take(100)}})
export const updateMedicineMeta=mutation({args:{medicineId:v.id('medicines'),barcode:v.optional(v.string()),reorderLevel:v.number(),expiryDate:v.optional(v.string())},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'stock_adjust'))return fail('FORBIDDEN','Inventory access is not allowed');if(args.reorderLevel<0)return fail('INVALID','Reorder level cannot be negative');const med=await ctx.db.get(args.medicineId);if(!med)return fail('NOT_FOUND','Medicine not found');await ctx.db.patch(med._id,{barcode:args.barcode?.trim()||undefined,reorderLevel:args.reorderLevel,expiryDate:args.expiryDate||undefined,updatedAt:Date.now()});return ok({})}})
export const createPrescription=mutation({args:{customerName:v.string(),customerPhone:v.string(),imageUrl:v.optional(v.string()),notes:v.optional(v.string())},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'prescriptions'))return fail('FORBIDDEN','Prescription access is not allowed');const id=await ctx.db.insert('prescriptions',{customerName:args.customerName,customerPhone:args.customerPhone,imageUrl:args.imageUrl,notes:args.notes,status:'pending',createdAt:Date.now(),updatedAt:Date.now()});return ok({id})}})
export const verifyPrescription=mutation({args:{id:v.id('prescriptions'),status:v.union(v.literal('approved'),v.literal('rejected')),rejectionReason:v.optional(v.string())},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'prescriptions'))return fail('FORBIDDEN','Prescription access is not allowed');await ctx.db.patch(args.id,{status:args.status,verifiedBy:s.name,rejectionReason:args.status==='rejected'?args.rejectionReason?.trim():undefined,updatedAt:Date.now()});await ctx.db.insert('auditLogs',{staffId:s._id,staffName:s.name,action:'prescription_verify',entityType:'prescription',entityId:String(args.id),details:args.status,createdAt:Date.now()});return ok({})}})
export const startShift=mutation({args:{openingCash:v.number()},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'cash_shift'))return fail('FORBIDDEN','Shift access is not allowed');const open=await ctx.db.query('staffShifts').withIndex('by_staff',q=>q.eq('staffId',s._id)).filter(q=>q.eq(q.field('status'),'open')).first();if(open)return fail('ALREADY_OPEN','A shift is already open');const id=await ctx.db.insert('staffShifts',{staffId:s._id,staffName:s.name,shopId:s.shopId,startedAt:Date.now(),openingCash:args.openingCash,expectedCash:args.openingCash,status:'open'});await ctx.db.insert('auditLogs',{staffId:s._id,staffName:s.name,action:'shift_start',entityType:'shift',entityId:String(id),details:'Opening cash ₹'+args.openingCash,createdAt:Date.now()});return ok({id})}})
export const closeShift=mutation({args:{shiftId:v.id('staffShifts'),actualCash:v.number()},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'cash_shift'))return fail('FORBIDDEN','Shift access is not allowed');const sh=await ctx.db.get(args.shiftId);if(!sh||String(sh.staffId)!==String(s._id)||sh.status!=='open')return fail('INVALID','Open shift not found');const diff=args.actualCash-sh.expectedCash;await ctx.db.patch(sh._id,{actualCash:args.actualCash,difference:diff,endedAt:Date.now(),status:'closed'});await ctx.db.insert('auditLogs',{staffId:s._id,staffName:s.name,action:'shift_close',entityType:'shift',entityId:String(sh._id),details:'Actual ₹'+args.actualCash+', difference ₹'+diff,createdAt:Date.now()});return ok({difference:diff})}})
export const createSale=mutation({args:{shiftId:v.id('staffShifts'),customerName:v.optional(v.string()),customerPhone:v.optional(v.string()),items:v.array(v.object({medicineId:v.id('medicines'),quantity:v.number()})),discount:v.number(),paymentMethod:v.union(v.literal('cash'),v.literal('upi'),v.literal('card'),v.literal('other')),prescriptionId:v.optional(v.id('prescriptions'))},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'billing'))return fail('FORBIDDEN','Billing access is not allowed');const sh=await ctx.db.get(args.shiftId);if(!sh||sh.status!=='open'||String(sh.staffId)!==String(s._id))return fail('SHIFT_REQUIRED','Start a shift first');if(args.discount<0||args.discount>s.maxDiscountPercent&&s.role!=='admin'&&s.role!=='manager')return fail('DISCOUNT','Discount exceeds your limit');const items:{medicineId:Id<'medicines'>,name:string,quantity:number,price:number,total:number}[]=[];let subtotal=0;for(const line of args.items){if(line.quantity<=0)return fail('QTY','Quantity must be positive');const med=await ctx.db.get(line.medicineId);if(!med||!med.active)return fail('MEDICINE','Medicine unavailable');if(med.stock<line.quantity)return fail('STOCK','Not enough stock for '+med.name);if(med.requiresPrescription){if(!args.prescriptionId)return fail('PRESCRIPTION','Approved prescription required for '+med.name);const rx=await ctx.db.get(args.prescriptionId);if(!rx||rx.status!=='approved')return fail('PRESCRIPTION','Prescription is not approved')}const total=med.price*line.quantity;subtotal+=total;items.push({medicineId:med._id,name:med.name,quantity:line.quantity,price:med.price,total})}const discount=Math.min(args.discount,subtotal),total=Math.max(0,subtotal-discount);for(const it of items){const med=await ctx.db.get(it.medicineId);if(!med)continue;await ctx.db.patch(med._id,{stock:med.stock-it.quantity,updatedAt:Date.now()});await ctx.db.insert('stockMovements',{staffId:s._id,staffName:s.name,medicineId:med._id,medicineName:med.name,type:'sale',quantity:-it.quantity,beforeStock:med.stock,afterStock:med.stock-it.quantity,createdAt:Date.now()})}const invoiceNo='WM-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+String(Date.now()).slice(-6);const id=await ctx.db.insert('staffSales',{staffId:s._id,staffName:s.name,shiftId:sh._id,customerName:args.customerName?.trim(),customerPhone:args.customerPhone?.trim(),items,subtotal,discount,total,paymentMethod:args.paymentMethod,status:'completed',createdAt:Date.now(),invoiceNo});if(args.customerPhone&&can(s,'customers'))await ctx.db.insert('customers',{name:args.customerName?.trim()||'Customer',phone:args.customerPhone.trim(),createdAt:Date.now(),updatedAt:Date.now()});if(args.paymentMethod==='cash')await ctx.db.patch(sh._id,{expectedCash:sh.expectedCash+total});await ctx.db.insert('auditLogs',{staffId:s._id,staffName:s.name,action:'sale_create',entityType:'sale',entityId:String(id),details:invoiceNo+' · ₹'+total,createdAt:Date.now()});return ok({id,total,invoiceNo})}})
export const adjustStock=mutation({args:{medicineId:v.id('medicines'),quantity:v.number(),type:v.union(v.literal('adjustment'),v.literal('damage'),v.literal('expired'),v.literal('purchase')),reason:v.string()},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'stock_adjust'))return fail('FORBIDDEN','Stock adjustment is not allowed');const med=await ctx.db.get(args.medicineId);if(!med)return fail('NOT_FOUND','Medicine not found');if(!args.reason.trim())return fail('REASON','Reason is required');const next=med.stock+args.quantity;if(next<0)return fail('STOCK','Stock cannot become negative');await ctx.db.patch(med._id,{stock:next,updatedAt:Date.now()});await ctx.db.insert('stockMovements',{staffId:s._id,staffName:s.name,medicineId:med._id,medicineName:med.name,type:args.type,quantity:args.quantity,beforeStock:med.stock,afterStock:next,reason:args.reason.trim(),createdAt:Date.now()});return ok({stock:next})}})
export const createReturn=mutation({args:{medicineId:v.id('medicines'),quantity:v.number(),reason:v.string(),disposition:v.union(v.literal('resellable'),v.literal('damaged'),v.literal('expired')),refundAmount:v.number()},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'returns'))return fail('FORBIDDEN','Returns are not allowed');const med=await ctx.db.get(args.medicineId);if(!med)return fail('NOT_FOUND','Medicine not found');if(args.quantity<=0||!args.reason.trim())return fail('INVALID','Quantity and reason are required');if(args.disposition==='resellable')await ctx.db.patch(med._id,{stock:med.stock+args.quantity,updatedAt:Date.now()});const id=await ctx.db.insert('staffReturns',{staffId:s._id,staffName:s.name,medicineId:med._id,medicineName:med.name,quantity:args.quantity,reason:args.reason,disposition:args.disposition,refundAmount:args.refundAmount,createdAt:Date.now()});return ok({id})}})
export const updateOrderStatus=mutation({args:{id:v.id('orders'),status:v.union(v.literal('preparing'),v.literal('ready_or_out'),v.literal('completed'),v.literal('cancelled'))},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'orders'))return fail('FORBIDDEN','Order access is not allowed');const o=await ctx.db.get(args.id);if(!o)return fail('NOT_FOUND','Order not found');await ctx.db.patch(o._id,{status:args.status});await ctx.db.insert('auditLogs',{staffId:s._id,staffName:s.name,action:'order_status',entityType:'order',entityId:String(o._id),details:o.status+' → '+args.status,createdAt:Date.now()});return ok({})}})
export const tasks=query({args:{},handler:async(ctx)=>{const s=await current(ctx);if(!s||!can(s,'tasks'))return [];return await ctx.db.query('staffTasks').order('desc').take(100)}})
export const updateTask=mutation({args:{id:v.id('staffTasks'),status:v.union(v.literal('pending'),v.literal('in_progress'),v.literal('completed'))},handler:async(ctx,args)=>{const s=await current(ctx);if(!s||!can(s,'tasks'))return fail('FORBIDDEN','Task access is not allowed');const t=await ctx.db.get(args.id);if(!t)return fail('NOT_FOUND','Task not found');await ctx.db.patch(t._id,{status:args.status,completedAt:args.status==='completed'?Date.now():undefined});return ok({})}})
export const reports=query({args:{},handler:async(ctx)=>{const s=await current(ctx);if(!s||!can(s,'reports'))return fail('FORBIDDEN','Reports access is not allowed');const sales=await ctx.db.query('staffSales').order('desc').take(500);const returns=await ctx.db.query('staffReturns').order('desc').take(200);const movements=await ctx.db.query('stockMovements').order('desc').take(200);const today=new Date().toISOString().slice(0,10);const td=sales.filter(x=>new Date(x.createdAt).toISOString().slice(0,10)===today&&x.status==='completed');return ok({todayTotal:td.reduce((n,x)=>n+x.total,0),todayBills:td.length,cash:td.filter(x=>x.paymentMethod==='cash').reduce((n,x)=>n+x.total,0),upi:td.filter(x=>x.paymentMethod==='upi').reduce((n,x)=>n+x.total,0),card:td.filter(x=>x.paymentMethod==='card').reduce((n,x)=>n+x.total,0),returns:returns.filter(x=>new Date(x.createdAt).toISOString().slice(0,10)===today).reduce((n,x)=>n+x.refundAmount,0),recentSales:td.slice(0,20),recentMovements:movements.slice(0,30)})}})
