import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { ArrowLeft, ArrowRight, ShoppingCart, Trash2, Plus, Minus, ShieldCheck, Truck, PackageCheck, Tag, Sparkles, CreditCard, MapPin } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { useCart } from '@/hooks/use-cart'
import { BrandLogo } from '@/components/brand'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'

export const Route = createFileRoute('/cart')({ head: () => ({ meta: [{ title: 'Your Cart — Wellcare Medicose' }] }), component: CartPage })
const formatINR = (n: number) => `₹${n.toFixed(2)}`
const COUPON_KEY = 'wellcare-coupon'

function CartPage() {
  const { lines, total, mrpTotal, changeQty } = useCart()
  const navigate = useNavigate()
  const [coupon, setCoupon] = useState(() => { try { return window.localStorage.getItem(COUPON_KEY) ?? '' } catch { return '' } })
  const discount = Math.max(0, mrpTotal - total)
  const delivery = total >= 499 || total === 0 ? 0 : 40
  function applyCoupon() {
    const code = coupon.trim().toUpperCase()
    if (!code) { toast.error('Enter a coupon code first'); return }
    try { window.localStorage.setItem(COUPON_KEY, code) } catch {}
    setCoupon(code)
    toast.success(`Coupon ${code} saved for checkout`)
  }

  return <div className="min-h-screen bg-[radial-gradient(circle_at_8%_0%,rgba(20,184,166,.17),transparent_28%),radial-gradient(circle_at_100%_18%,rgba(59,130,246,.12),transparent_25%),linear-gradient(135deg,#f7fbfc,#edf7fb_55%,#f8fafc)]">
    <header className="sticky top-0 z-30 border-b border-white/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-3 sm:px-6"><button onClick={() => navigate({to:'/',replace:true})} aria-label="Back to shopping" className="flex size-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm"><ArrowLeft className="size-5"/></button><BrandLogo/><div className="ml-auto hidden items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 sm:flex"><ShieldCheck className="size-4"/> Secure cart</div></div></header>
    <main className="mx-auto max-w-7xl px-3 py-5 pb-12 sm:px-6 sm:py-8">
      <div className="mb-6 overflow-hidden rounded-[28px] bg-gradient-to-r from-[#063b42] via-[#087f7b] to-[#0b5ea8] p-5 text-white shadow-[0_24px_55px_-30px_rgba(8,127,123,.7)] sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-cyan-100"><Sparkles className="size-4"/> Wellcare Medicose</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Your Shopping Cart</h1><p className="mt-2 max-w-xl text-sm text-cyan-50/85">Review your healthcare essentials, update quantities and continue to a smooth checkout.</p></div><div className="flex size-20 items-center justify-center rounded-3xl border border-white/20 bg-white/10 shadow-inner backdrop-blur"><ShoppingCart className="size-10"/></div></div><div className="mt-6 grid grid-cols-3 gap-2 sm:max-w-xl">{[['01','Your cart'],['02','Fulfilment'],['03','Checkout']].map(([n,label],i)=><div key={n} className={`rounded-xl border px-3 py-2.5 ${i===0?'border-white/35 bg-white/20':'border-white/10 bg-white/5'}`}><p className="text-[10px] font-black text-cyan-100">{n}</p><p className="mt-1 text-xs font-bold">{label}</p></div>)}</div></div>
      {lines.length===0 ? <section className="flex min-h-[390px] flex-col items-center justify-center rounded-3xl border border-white/80 bg-white/75 p-8 text-center shadow-xl shadow-slate-200/40"><span className="flex size-24 items-center justify-center rounded-[28px] bg-gradient-to-br from-emerald-100 to-cyan-100 text-primary shadow-inner"><ShoppingCart className="size-11"/></span><h2 className="mt-5 text-2xl font-black text-slate-900">Your cart is empty</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">Explore medicines and everyday health essentials for you and your family.</p><Button className="mt-5 h-12 rounded-xl bg-gradient-to-r from-primary to-brand-blue px-6 font-bold" onClick={()=>navigate({to:'/'})}>Continue shopping <ArrowRight className="ml-2 size-4"/></Button></section> :
      <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
        <div className="space-y-4"><section className="rounded-3xl border border-white/80 bg-white/80 p-4 shadow-lg shadow-slate-200/30 backdrop-blur sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-black text-slate-900">Cart items <span className="text-primary">({lines.length})</span></h2><p className="mt-1 text-xs text-slate-500">Manage quantities before placing your order.</p></div><button onClick={()=>lines.forEach(line=>changeQty(line.medicineId,-line.quantity))} className="rounded-xl border border-rose-100 bg-rose-50 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-100">Clear cart</button></div><div className="space-y-3">{lines.map((line,i)=><article key={line.medicineId} className="rounded-2xl border border-slate-100 bg-gradient-to-r from-white to-cyan-50/40 p-3 transition hover:border-emerald-200 hover:shadow-md sm:p-4"><div className="flex gap-3"><div className="flex size-16 shrink-0 items-center justify-center rounded-2xl border border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-sky-50 text-primary"><PackageCheck className="size-7"/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-extrabold leading-5 text-slate-800">{line.name}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-wide text-slate-400">Healthcare essential · Item {i+1}</p></div><button aria-label={`Remove ${line.name}`} onClick={()=>changeQty(line.medicineId,-line.quantity)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="size-4"/></button></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><span className="text-lg font-black text-[#087f7b]">{formatINR(line.price)}</span>{line.mrpPrice && line.mrpPrice>line.price && <span className="ml-2 text-xs text-slate-400 line-through">{formatINR(line.mrpPrice)}</span>}</div><div className="inline-flex items-center gap-1 rounded-xl border border-slate-200 bg-white p-1"><Button variant="ghost" size="icon" className="size-8 rounded-lg" onClick={()=>changeQty(line.medicineId,-1)} aria-label="Decrease quantity"><Minus className="size-3.5"/></Button><span className="w-7 text-center text-sm font-black tabular-nums">{line.quantity}</span><Button variant="ghost" size="icon" className="size-8 rounded-lg" onClick={()=>changeQty(line.medicineId,1)} aria-label="Increase quantity"><Plus className="size-3.5"/></Button></div></div></div></div></article>)}</div></section>
        <section className="rounded-3xl border border-emerald-100 bg-gradient-to-r from-emerald-50 to-cyan-50 p-4 sm:p-5"><h3 className="flex items-center gap-2 font-black text-emerald-950"><Truck className="size-5"/> Fulfilment options</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-emerald-200 bg-white/80 p-3"><Truck className="size-5 text-emerald-700"/><p className="mt-2 text-sm font-bold text-slate-800">Home delivery</p><p className="mt-1 text-xs text-slate-500">Convenient delivery to your address.</p></div><div className="rounded-2xl border border-sky-200 bg-white/80 p-3"><MapPin className="size-5 text-sky-700"/><p className="mt-2 text-sm font-bold text-slate-800">Store pickup</p><p className="mt-1 text-xs text-slate-500">Pick up your order from the store.</p></div></div></section>
        <section className="rounded-3xl border border-white/80 bg-white/80 p-4 shadow-sm sm:p-5"><h3 className="mb-3 flex items-center gap-2 font-black text-slate-800"><Tag className="size-4 text-primary"/> Apply a coupon</h3><div className="flex gap-2"><Input value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} placeholder="Coupon code" className="h-11 rounded-xl uppercase"/><Button variant="outline" className="h-11 rounded-xl border-primary/30 font-bold text-primary" onClick={applyCoupon}>Apply</Button></div></section></div>
        <aside className="lg:sticky lg:top-24"><section className="overflow-hidden rounded-3xl border border-white/80 bg-white/90 shadow-[0_22px_55px_-30px_rgba(15,118,110,.5)] backdrop-blur"><div className="bg-gradient-to-r from-[#075e63] to-[#0b6fae] p-5 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-100">Order summary</p><h2 className="mt-1 text-xl font-black">{lines.length} items in your cart</h2><p className="mt-1 text-xs text-white/75">A quick review before checkout</p></div><div className="space-y-3 p-5 text-sm"><div className="flex justify-between text-slate-500"><span>MRP total</span><span>{formatINR(mrpTotal)}</span></div>{discount>0&&<div className="flex justify-between font-bold text-emerald-600"><span>You save</span><span>−{formatINR(discount)}</span></div>}<div className="flex justify-between text-slate-500"><span>Delivery estimate</span><span className={delivery===0?'font-bold text-emerald-600':'font-semibold text-slate-700'}>{delivery===0?'FREE':formatINR(delivery)}</span></div><Separator/><div className="flex items-end justify-between gap-2"><span className="font-black text-slate-800">Total payable</span><span className="text-2xl font-black text-[#087f7b]">{formatINR(total+delivery)}</span></div>{discount>0&&<div className="rounded-xl bg-emerald-50 p-3 text-center text-xs font-bold text-emerald-700">🎉 You're saving {formatINR(discount)}</div>}<Button className="mt-2 h-12 w-full rounded-xl bg-gradient-to-r from-[#087f7b] to-[#0b6fae] font-black shadow-lg" onClick={()=>navigate({to:'/checkout'})}>Proceed to checkout <ArrowRight className="ml-2 size-4"/></Button><div className="flex items-center justify-center gap-2 pt-1 text-[10px] font-semibold text-slate-500"><ShieldCheck className="size-4 text-emerald-600"/> Secure checkout <span>•</span><CreditCard className="size-4 text-sky-600"/> Payment options</div></div></section><Link to="/" className="mt-4 flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white/70 px-4 py-3 text-sm font-bold text-slate-600 hover:bg-white"><ArrowLeft className="size-4"/> Continue shopping</Link></aside>
      </div>}
    </main>
  </div>
}
