import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { useMutation } from 'convex/react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Store, Truck, Smartphone, CreditCard, Banknote, Wallet, Lock, CheckCircle2, MessageCircle, MapPinned, Check, Clock3, UserRound, Phone, FileText, ChevronRight, PackageCheck, Sparkles, ArrowRight, ShoppingBag } from 'lucide-react'
import { api } from '../../convex/_generated/api'
import { useCart, type CartLine } from '@/hooks/use-cart'
import { saveLastPhone } from '@/hooks/use-recently-viewed'
import { MapAddressPicker, type SelectedDeliveryLocation } from '@/components/map-address-picker'
import { BrandLogo } from '@/components/brand'
import { STORE_LOCATION } from '@/config/store-location'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'

export const Route = createFileRoute('/checkout')({ head: () => ({ meta: [{ title: 'Checkout — Wellcare Medicose' }] }), component: CheckoutPage })
const STORE_WHATSAPP = '917088252556'
const COUPON_KEY = 'wellcare-coupon'
function formatINR(n: number) { return `₹${n.toFixed(2)}` }
function shortOrderId(id: string) { return id.slice(-8).toUpperCase() }
function buildWhatsAppMessage(args: { orderId: string; total: number; customerName: string; fulfillment: 'pickup' | 'delivery'; deliveryAddress?: string; items: CartLine[] }) {
  return [`New order — ${shortOrderId(args.orderId)}`, '', `Name: ${args.customerName}`, args.fulfillment === 'delivery' ? `Delivery address: ${args.deliveryAddress ?? ''}` : 'Fulfillment: Store pickup', '', 'Items:', ...args.items.map((l) => `${l.quantity} x ${l.name} — ${formatINR(l.price * l.quantity)}`), '', `Total: ${formatINR(args.total)}`].join('\n')
}
function CheckoutPage() {
  const { lines, total, mrpTotal, clearCart } = useCart()
  const navigate = useNavigate()
  const placeOrder = useMutation(api.orders.placeV2)
  const [fulfillment, setFulfillment] = useState<'pickup' | 'delivery'>('pickup')
  const [paymentMethod, setPaymentMethod] = useState<'upi' | 'card' | 'wallet' | 'cod'>('cod')
  const [customerName, setCustomerName] = useState('')
  const [customerPhone, setCustomerPhone] = useState('')
  const [address, setAddress] = useState('')
  const [deliveryPoint, setDeliveryPoint] = useState<SelectedDeliveryLocation | null>(null)
  const [mapOpen, setMapOpen] = useState(false)
  const [deliveryTimePref, setDeliveryTimePref] = useState('')
  const [notes, setNotes] = useState('')
  const [couponCode, setCouponCode] = useState('')
  const [placing, setPlacing] = useState(false)
  const [confirmed, setConfirmed] = useState<{ orderId: string; total: number; customerName: string; fulfillment: 'pickup' | 'delivery'; deliveryAddress?: string; items: CartLine[] } | null>(null)
  useEffect(() => { try { const saved = window.localStorage.getItem(COUPON_KEY); if (saved) setCouponCode(saved) } catch { /* ignore */ } }, [])
  const deliveryCharge = fulfillment === 'pickup' ? 0 : total >= 499 ? 0 : 40
  const mrpDiscount = Math.max(0, mrpTotal - total)
  const deliveryDistanceKm = deliveryPoint ? (() => {
    const rad = (n: number) => n * Math.PI / 180
    const a = Math.sin(rad(deliveryPoint.lat - STORE_LOCATION.lat) / 2) ** 2 + Math.cos(rad(STORE_LOCATION.lat)) * Math.cos(rad(deliveryPoint.lat)) * Math.sin(rad(deliveryPoint.lng - STORE_LOCATION.lng) / 2) ** 2
    return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
  })() : null
  const deliveryEstimate = deliveryDistanceKm === null ? null : deliveryDistanceKm <= 3 ? '30–45 min' : deliveryDistanceKm <= 7 ? '45–75 min' : deliveryDistanceKm <= 12 ? '60–90 min' : 'Timing to be confirmed'
  async function handlePlaceOrder() {
    if (lines.length === 0) { toast.error('Your cart is empty'); return }
    if (!customerName.trim() || !customerPhone.trim()) { toast.error('Please enter your name and phone number'); return }
    if (fulfillment === 'delivery' && !address.trim()) { toast.error('Please enter a delivery address'); return }
    setPlacing(true)
    try {
      const result = await placeOrder({ customerName, customerPhone, fulfillment, deliveryAddress: fulfillment === 'delivery' ? address : undefined, deliveryTimePref: deliveryTimePref || undefined, paymentMethod, couponCode: couponCode.trim() || undefined, items: lines.map((l) => ({ medicineId: l.medicineId as any, quantity: l.quantity })), notes: notes || undefined })
      saveLastPhone(customerPhone.trim())
      try { window.localStorage.removeItem(COUPON_KEY) } catch { /* ignore */ }
      setConfirmed({ orderId: result.orderId, total: result.total, customerName, fulfillment, deliveryAddress: fulfillment === 'delivery' ? address : undefined, items: lines })
      clearCart()
    } catch (err) { toast.error(err instanceof Error ? err.message : 'Could not place order') }
    finally { setPlacing(false) }
  }
  if (lines.length === 0 && !confirmed) return <div className="mx-auto max-w-lg px-4 py-16 text-center"><p className="text-sm text-muted-foreground">Your cart is empty.</p><Link to="/" className="mt-4 inline-block text-sm text-primary underline">Continue shopping</Link></div>
  const methods = [{ key: 'upi', label: 'UPI', icon: Smartphone }, { key: 'card', label: 'Card', icon: CreditCard }, { key: 'wallet', label: 'Wallet', icon: Wallet }, { key: 'cod', label: 'Cash on Delivery', icon: Banknote }] as const
  return <div className="relative min-h-screen overflow-x-hidden bg-[#edf7f6] pb-40 text-slate-900">
    <div className="pointer-events-none fixed inset-0 overflow-hidden">
      <div className="absolute -left-32 top-20 size-80 rounded-full bg-emerald-300/20 blur-3xl" />
      <div className="absolute -right-28 top-48 size-96 rounded-full bg-blue-300/20 blur-3xl" />
    </div>
    <header className="sticky top-0 z-40 border-b border-white/80 bg-white/75 backdrop-blur-2xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary">Secure checkout · Step 1 of 2</p><h1 className="mt-1 text-xl font-black tracking-tight text-slate-900">Delivery & payment</h1><p className="mt-0.5 text-xs text-slate-500">Choose how you want your Wellcare order fulfilled</p></div><BrandLogo /></div>
    </header>
    <main className="relative z-10 mx-auto max-w-5xl space-y-5 px-4 py-5 sm:px-6 sm:py-7">
      <section className="rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-[0_18px_55px_-40px_rgba(15,118,110,.5)] backdrop-blur-2xl sm:p-5">
        <div className="mb-4 flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-sm font-black text-white shadow-lg shadow-primary/20">1</span><div><p className="text-[10px] font-black uppercase tracking-wider text-primary">Fulfilment</p><Label className="text-lg font-black text-slate-900">Choose how you want it</Label></div></div>
        <div className="mt-4 grid grid-cols-2 gap-3" role="radiogroup" aria-label="Order fulfillment">
          {([{ value: 'delivery', title: 'Home Delivery', desc: 'Delivered to your doorstep', icon: Truck }, { value: 'pickup', title: 'Store Pickup', desc: 'Collect from our store', icon: Store }] as const).map(({ value, title, desc, icon: Icon }) => {
            const selected = fulfillment === value
            return <button key={value} type="button" role="radio" aria-checked={selected} onClick={() => { setFulfillment(value); if (value === 'delivery' && !address) setMapOpen(true) }} className={cn('relative flex min-h-32 flex-col items-start gap-2 rounded-2xl border-2 p-3 text-left transition-all', selected ? 'border-primary bg-emerald-50/70 shadow-sm' : 'border-slate-200 bg-white hover:border-primary/40')}>
              <span className={cn('flex size-11 items-center justify-center rounded-2xl', selected ? 'bg-primary text-white' : 'bg-slate-100 text-primary')}><Icon className="size-5" /></span><span className="text-sm font-bold text-slate-900">{title}</span><span className="text-xs leading-relaxed text-slate-500">{desc}</span>{selected && <span className="absolute right-3 top-3 flex size-5 items-center justify-center rounded-full bg-primary text-white"><Check className="size-3" /></span>}
            </button>
          })}
        </div>
      </section>
      {fulfillment === 'pickup' ? <section className="flex gap-3 rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-sm backdrop-blur-2xl"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-blue-50 text-primary"><Store className="size-5" /></span><div><p className="font-semibold text-slate-900">Collect from Wellcare Medicose</p><p className="mt-1 text-sm text-slate-600">{STORE_LOCATION.label}</p><p className="mt-1 text-xs text-slate-500">Open 24×7 · No delivery address needed for pickup.</p></div></section> : <>
        <section className="space-y-3 rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-[0_18px_55px_-40px_rgba(15,118,110,.5)] backdrop-blur-2xl sm:p-5">
          <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-black text-white">3</span><div><p className="text-[10px] font-black uppercase tracking-wider text-primary">Location</p><p className="text-lg font-black text-slate-900">Deliver to</p><p className="mt-0.5 text-xs text-slate-500">Confirm your precise drop-off point</p></div></div><Button type="button" variant="outline" className="shrink-0 rounded-xl" onClick={() => setMapOpen(true)}><MapPinned className="mr-2 size-4" />{address ? 'Edit location' : 'Pin on map'}</Button></div>
          <div className="flex gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4" aria-live="polite"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-rose-100 text-rose-600"><MapPinned className="size-6" /></span><div className="min-w-0">{address ? <><p className="text-sm font-semibold text-slate-900">{address}</p><p className="mt-2 flex items-center gap-1.5 text-xs font-medium text-emerald-700"><CheckCircle2 className="size-3.5" /> Map pin selected · verify address</p></> : <><p className="font-semibold text-slate-800">Add delivery location</p><p className="mt-1 text-sm text-slate-500">Use the map pin to choose your doorstep address.</p></>}</div></div>
          <button type="button" onClick={() => setMapOpen(true)} className="flex w-full items-center justify-between rounded-xl border border-dashed border-primary/40 bg-primary/[0.03] px-4 py-3 text-left text-sm font-semibold text-primary hover:bg-primary/[0.06]"><span className="flex items-center gap-2"><MapPinned className="size-4" />Open map and adjust pin</span><ChevronRight className="size-4" /></button>
        </section>
        <section aria-live="polite" className="flex items-center gap-3 rounded-[1.5rem] border border-emerald-200/70 bg-gradient-to-r from-emerald-50/90 to-cyan-50/80 p-4 shadow-sm backdrop-blur-xl"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-emerald-600 text-white"><Clock3 className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-emerald-800">Estimated delivery</p><p className="mt-0.5 text-xl font-extrabold tracking-tight text-emerald-800">{deliveryEstimate ?? 'Choose your location'}</p><p className="text-xs leading-relaxed text-emerald-800/80">{deliveryDistanceKm === null ? 'Pin your address to see an indicative delivery window.' : deliveryDistanceKm > 12 ? 'We’ll confirm delivery coverage and timing before dispatch.' : `Indicative estimate based on straight-line distance (${deliveryDistanceKm.toFixed(1)} km). Traffic and preparation time can change actual delivery.`}</p></div><Truck className="size-7 shrink-0 text-emerald-700" /></section>
      </>}
      <section className="rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-[0_18px_55px_-40px_rgba(15,118,110,.5)] backdrop-blur-2xl sm:p-5"><div className="mb-4 flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-sm font-black text-white">4</span><Clock3 className="size-4 text-primary" /><Label htmlFor="time-pref" className="font-bold text-slate-900">Preferred {fulfillment === 'pickup' ? 'pickup' : 'delivery'} time <span className="font-normal text-slate-400">(optional)</span></Label></div><Input id="time-pref" className="h-12 rounded-xl bg-slate-50" value={deliveryTimePref} onChange={(e) => setDeliveryTimePref(e.target.value)} placeholder="e.g. Evening after 6 PM" /></section>
      <section className="rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-[0_18px_55px_-40px_rgba(15,118,110,.5)] backdrop-blur-2xl sm:p-5"><div className="mb-4 flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-sm font-black text-white">5</span><UserRound className="size-4 text-primary" /><h2 className="text-base font-bold text-slate-900">Contact details</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="name">Your name</Label><Input id="name" className="h-12 rounded-xl bg-slate-50" value={customerName} onChange={(e) => setCustomerName(e.target.value)} placeholder="Enter your full name" /></div><div className="space-y-1.5"><Label htmlFor="phone">Phone number</Label><div className="relative"><Phone className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input id="phone" className="h-12 rounded-xl bg-slate-50 pl-10" value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)} placeholder="Enter mobile number" inputMode="tel" /></div></div></div><div className="mt-4 space-y-1.5"><Label htmlFor="notes">Order notes <span className="font-normal text-slate-400">(optional)</span></Label><div className="relative"><FileText className="absolute left-3 top-3 size-4 text-slate-400" /><Textarea id="notes" className="min-h-24 rounded-xl bg-slate-50 pl-10" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Any special instructions? (e.g. call before delivery)" /></div></div></section>
      <section className="rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-[0_18px_55px_-40px_rgba(15,118,110,.5)] backdrop-blur-2xl sm:p-5"><div className="mb-4 flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-sm font-black text-white">6</span><CreditCard className="size-4 text-primary" /><h2 className="text-base font-bold text-slate-900">Payment method</h2></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{methods.map(({ key, label, icon: Icon }) => <button key={key} type="button" aria-pressed={paymentMethod === key} onClick={() => setPaymentMethod(key)} className={cn('flex min-h-20 flex-col items-start justify-between gap-2 rounded-xl border p-3 text-left text-sm font-semibold transition-colors', paymentMethod === key ? 'border-primary bg-emerald-50 text-slate-900 ring-1 ring-primary/20' : 'border-slate-200 bg-white text-slate-600 hover:border-primary/40')}><span className="flex size-9 items-center justify-center rounded-xl bg-slate-100 text-primary"><Icon className="size-4" /></span><span className="flex w-full items-center justify-between gap-1">{label}{paymentMethod === key && <CheckCircle2 className="size-4 text-primary" />}</span></button>)}</div><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Lock className="size-3.5 text-emerald-700" />Secure order processing</p></section>
      <section className="rounded-[1.75rem] border border-white/90 bg-white/65 p-4 shadow-[0_18px_55px_-40px_rgba(15,118,110,.5)] backdrop-blur-2xl sm:p-5"><div className="mb-4 flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary text-sm font-black text-white">7</span><div><p className="text-[10px] font-black uppercase tracking-wider text-primary">Final review</p><h2 className="text-lg font-black text-slate-900">Order summary</h2></div></div><div className="space-y-3 text-sm"><div className="flex justify-between text-slate-500"><span>MRP total</span><span>{formatINR(mrpTotal)}</span></div>{mrpDiscount > 0 && <div className="flex justify-between font-medium text-emerald-700"><span>Discount</span><span>−{formatINR(mrpDiscount)}</span></div>}<div className="flex justify-between text-slate-500"><span>Delivery charges</span><span className={deliveryCharge === 0 ? 'font-semibold text-emerald-700' : ''}>{deliveryCharge === 0 ? 'FREE' : formatINR(deliveryCharge)}</span></div><div className="flex justify-between text-slate-500"><span>Taxes and charges</span><span>Included</span></div><div className="flex justify-between border-t border-dashed border-slate-200 pt-4 text-base font-extrabold text-slate-900"><span>Total amount</span><span>{formatINR(total + deliveryCharge)}</span></div></div></section>
    </main>
    <div className="fixed inset-x-0 bottom-16 z-30 lg:bottom-0 border-t border-white/80 bg-white/80 px-4 py-3 shadow-[0_-8px_30px_rgba(15,23,42,0.08)] backdrop-blur-xl"><div className="mx-auto flex max-w-3xl items-center justify-between gap-4"><div><p className="text-[11px] font-medium text-slate-500">Total amount</p><p className="text-xl font-extrabold tracking-tight text-slate-900">{formatINR(total + deliveryCharge)}</p></div><Button size="lg" className="min-w-40 rounded-xl px-6 font-bold shadow-md" disabled={placing} onClick={handlePlaceOrder}>{placing ? 'Placing order…' : <>Place Order <ChevronRight className="ml-2 size-4" /></>}</Button></div></div>
    <MapAddressPicker open={mapOpen} onOpenChange={setMapOpen} onConfirm={(location) => { setAddress(location.address); setDeliveryPoint(location) }} />
    {confirmed && (
      <div className="fixed inset-0 z-[100] h-[100dvh] overflow-hidden bg-[#edf8f7] text-slate-900">
        <div className="flex h-full flex-col overflow-hidden">
          <header className="shrink-0 border-b border-white/80 bg-white/85 px-4 py-3 shadow-sm backdrop-blur-2xl sm:px-6">
            <div className="mx-auto flex max-w-7xl items-center justify-between gap-3">
              <div className="flex min-w-0 items-center gap-3">
                <div className="flex size-10 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500 to-cyan-600 text-white shadow-lg"><CheckCircle2 className="size-5" /></div>
                <div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-emerald-700">Wellcare Medicose · Order confirmed</p><h1 className="truncate text-base font-black tracking-tight sm:text-xl">Your Healthcare Journey</h1></div>
              </div>
              <div className="flex shrink-0 items-center gap-2"><span className="hidden rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-[10px] font-extrabold text-emerald-700 sm:inline-flex">Payment successful</span><BrandLogo /></div>
            </div>
          </header>
          <main className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-3 py-3 sm:px-5 sm:py-4">
            <div className="mx-auto grid max-w-7xl gap-2.5 lg:grid-cols-12">
              <section className="overflow-hidden rounded-2xl border border-white bg-white shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4">
                <div className="relative overflow-hidden bg-gradient-to-br from-emerald-50 via-white to-cyan-50 p-4 sm:p-5"><div className="absolute -right-8 -top-10 size-28 rounded-full bg-emerald-200/40 blur-2xl" /><div className="relative"><div className="flex items-start justify-between gap-3"><div className="flex size-14 items-center justify-center rounded-full bg-white shadow-md ring-4 ring-white/70"><div className="flex size-9 items-center justify-center rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 text-white"><CheckCircle2 className="size-6" /></div></div><span className="rounded-full bg-emerald-600 px-2.5 py-1 text-[9px] font-black text-white">CONFIRMED</span></div><h2 className="mt-3 text-xl font-black">Order Confirmed! 🎉</h2><p className="mt-1 text-xs text-slate-500">Your order has been successfully placed.</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-white/80 p-2.5"><p className="text-[9px] font-bold uppercase text-slate-400">Order ID</p><p className="mt-1 font-black">#{shortOrderId(confirmed.orderId)}</p></div><div className="rounded-xl bg-white/80 p-2.5"><p className="text-[9px] font-bold uppercase text-slate-400">Total paid</p><p className="mt-1 font-black text-primary">{formatINR(confirmed.total)}</p></div></div></div></div>
                <div className="grid grid-cols-4 gap-2 border-t border-slate-100 p-3">{[['Medicine', confirmed.items.length], ['Lab Test', 0], ['Consult', 0], ['Pickup', confirmed.fulfillment === 'pickup' ? 1 : 0]].map(([label, count]) => <div key={String(label)} className="rounded-xl bg-slate-50 p-2 text-center"><PackageCheck className="mx-auto size-4 text-primary" /><p className="mt-1 text-[9px] font-bold text-slate-600">{label}</p><p className="text-[9px] text-slate-400">({count})</p></div>)}</div>
                <div className="border-t border-slate-100 p-3"><div className="rounded-xl bg-gradient-to-r from-emerald-600 to-cyan-600 p-3 text-white"><p className="text-[9px] font-bold uppercase tracking-wider text-white/75">{confirmed.fulfillment === 'delivery' ? 'Estimated delivery' : 'Pickup status'}</p><p className="mt-0.5 text-lg font-black">{confirmed.fulfillment === 'delivery' ? 'Today · 30–90 min' : 'Ready after preparation'}</p><p className="mt-1 text-[10px] text-white/80">{confirmed.fulfillment === 'delivery' ? 'You can track the rider live once dispatched.' : 'We will notify you when your order is ready.'}</p></div><Link to="/track/$orderId" params={{ orderId: confirmed.orderId }} className="mt-2 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-xs font-extrabold text-white shadow-sm"><PackageCheck className="size-4" /> Track Your Order <ArrowRight className="size-3.5" /></Link></div>
              </section>

              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-primary">02 · Journey</p><h2 className="text-base font-black">Your Healthcare Journey</h2></div><Sparkles className="size-5 text-emerald-500" /></div><div className="relative mt-4 space-y-3 pl-1"><div className="absolute bottom-4 left-3 top-3 w-px bg-emerald-200" />{[['Order Confirmed','Just now',true],['Pharmacy Preparing','In progress',true],['Packed',confirmed.fulfillment === 'pickup' ? 'Preparing for pickup' : 'Next step',false],[confirmed.fulfillment === 'pickup' ? 'Ready for Pickup' : 'Out for Delivery',confirmed.fulfillment === 'pickup' ? 'We’ll notify you' : 'Coming soon',false],['Delivered','Pending',false]].map(([title, sub, done], i) => <div key={String(title)} className="relative flex items-center gap-3"><span className={cn('z-10 flex size-6 shrink-0 items-center justify-center rounded-full border-2 bg-white', done ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-slate-300 text-slate-300')}>{done ? <Check className="size-3" /> : <span className="text-[8px] font-black">{i + 1}</span>}</span><div className={cn('min-w-0 flex-1 rounded-xl px-3 py-2', done ? 'bg-emerald-50' : 'bg-slate-50')}><p className="text-xs font-bold">{title}</p><p className="text-[9px] text-slate-500">{sub}</p></div></div>)}</div><div className="mt-3 rounded-xl border border-blue-100 bg-blue-50/70 p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-black text-blue-800">Live Tracking</p><span className="flex items-center gap-1 text-[9px] font-bold text-emerald-700"><span className="size-1.5 animate-pulse rounded-full bg-emerald-500" /> Live</span></div><div className="relative mt-2 h-24 overflow-hidden rounded-xl bg-[linear-gradient(135deg,#dff4e8_0%,#eef7ff_48%,#dbeafe_100%)]"><div className="absolute left-4 top-8 h-px w-[72%] rotate-12 bg-blue-500/50" /><div className="absolute left-[22%] top-[58%] size-3 rounded-full border-2 border-white bg-blue-600 shadow" /><div className="absolute right-[17%] top-[24%] flex size-8 items-center justify-center rounded-full bg-emerald-600 text-white shadow-lg"><MapPinned className="size-4" /></div><Truck className="absolute bottom-3 left-[42%] size-7 text-blue-700" /></div><p className="mt-2 text-[9px] text-slate-500">{confirmed.fulfillment === 'delivery' ? 'Rider tracking will activate after dispatch.' : 'Pickup tracking will update when the store prepares your order.'}</p></div></section>

              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-primary">03 · Order details</p><h2 className="text-base font-black">Order Details</h2></div><span className="rounded-lg bg-slate-50 px-2 py-1 text-[9px] font-bold text-slate-500">Confirmed</span></div><div className="mt-3 space-y-2"><div className="rounded-xl border border-slate-100 p-3"><div className="flex items-center gap-2"><Truck className="size-4 text-emerald-600" /><p className="text-[10px] font-bold text-slate-500">Fulfilment method</p></div><p className="mt-1 text-sm font-black">{confirmed.fulfillment === 'delivery' ? 'Express Delivery' : 'Store Pickup'}</p></div><div className="rounded-xl border border-slate-100 p-3"><div className="flex items-center gap-2"><MapPinned className="size-4 text-blue-600" /><p className="text-[10px] font-bold text-slate-500">{confirmed.fulfillment === 'delivery' ? 'Delivery address' : 'Store location'}</p></div><p className="mt-1 text-xs font-semibold leading-5">{confirmed.fulfillment === 'delivery' ? (confirmed.deliveryAddress ?? 'Address saved with order') : STORE_LOCATION.label}</p></div><div className="rounded-xl border border-slate-100 p-3"><div className="flex items-center gap-2"><Lock className="size-4 text-emerald-600" /><p className="text-[10px] font-bold text-slate-500">Payment</p></div><p className="mt-1 text-sm font-black">Payment successful</p><p className="text-[9px] text-slate-400">Securely processed by Wellcare</p></div><div className="flex items-center justify-between rounded-xl bg-emerald-50 px-3 py-2.5"><span className="flex items-center gap-2 text-xs font-bold text-emerald-800"><CheckCircle2 className="size-4" /> Prescription status</span><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black text-emerald-700">Verified</span></div></div></section>

              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-8"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-primary">04 · Items</p><h2 className="text-base font-black">Items in Your Order</h2></div><span className="text-[10px] font-bold text-slate-400">{confirmed.items.length} item{confirmed.items.length === 1 ? '' : 's'}</span></div><div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-100">{confirmed.items.map((item) => <div key={item.medicineId} className="flex items-center gap-3 p-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-primary"><PackageCheck className="size-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{item.name}</p><p className="text-[9px] text-slate-400">Qty: {item.quantity}</p></div><p className="text-sm font-black text-primary">{formatINR(item.price * item.quantity)}</p></div>)}</div></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">05 · Price breakdown</p><h2 className="text-base font-black">Payment Summary</h2><div className="mt-3 space-y-2 text-xs"><div className="flex justify-between"><span className="text-slate-500">Items total</span><b>{formatINR(confirmed.total)}</b></div><div className="flex justify-between"><span className="text-slate-500">Delivery fee</span><b className="text-emerald-700">FREE</b></div><div className="flex justify-between"><span className="text-slate-500">Savings</span><b className="text-emerald-700">Applied</b></div><div className="mt-2 flex items-center justify-between rounded-xl bg-emerald-50 p-3 text-emerald-800"><span className="font-bold">Total Paid</span><span className="text-lg font-black">{formatINR(confirmed.total)}</span></div></div></section>

              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">06 · Prescription & consultation</p><h2 className="text-base font-black">Care Support</h2><div className="mt-3 rounded-xl bg-gradient-to-r from-indigo-600 to-blue-600 p-3 text-white"><div className="flex items-center gap-2"><CheckCircle2 className="size-5" /><div><p className="text-xs font-black">Prescription Verified</p><p className="text-[9px] text-white/75">Your order is cleared for processing.</p></div></div></div><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => toast.info('Prescription details will be available from your order record.')} className="rounded-xl border border-slate-200 p-2.5 text-[10px] font-bold hover:bg-slate-50">View Details</button><button type="button" onClick={() => toast.info('Consultation can be scheduled from your account.')} className="rounded-xl border border-slate-200 p-2.5 text-[10px] font-bold hover:bg-slate-50">Consultation</button></div></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">07 · Lab test & home sample</p><h2 className="text-base font-black">Diagnostics</h2><div className="mt-3 rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-500 p-3 text-white"><p className="text-xs font-black">Home Sample Collection</p><p className="mt-1 text-[9px] text-white/80">No lab test added to this order.</p></div><button type="button" onClick={() => navigate({ to: '/' })} className="mt-2 flex w-full items-center justify-between rounded-xl border border-slate-200 px-3 py-2.5 text-left text-[10px] font-bold"><span>Explore diagnostics</span><ChevronRight className="size-4" /></button></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">08 · Store pickup</p><h2 className="text-base font-black">Pickup Information</h2><div className={cn('mt-3 rounded-xl p-3 text-white', confirmed.fulfillment === 'pickup' ? 'bg-gradient-to-r from-emerald-600 to-teal-600' : 'bg-gradient-to-r from-slate-700 to-slate-800')}><p className="text-xs font-black">{confirmed.fulfillment === 'pickup' ? 'Ready for Pickup' : 'Delivery selected'}</p><p className="mt-1 text-[9px] text-white/80">{STORE_LOCATION.label}</p></div><button type="button" onClick={() => toast.info(confirmed.fulfillment === 'pickup' ? 'Pickup details will update when the order is ready.' : 'Store pickup is available for future orders.')} className="mt-2 flex w-full items-center justify-between rounded-xl border border-slate-200 px-3 py-2.5 text-left text-[10px] font-bold"><span>View store details</span><ChevronRight className="size-4" /></button></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">09 · Additional options</p><h2 className="text-base font-black">Make It Easier</h2><div className="mt-3 grid grid-cols-2 gap-2">{[['Reschedule','Change timing',Clock3],['Wishlist','Save for later',Sparkles],['Refill reminder','Never miss a dose',Clock3],['Buy again','Order history',ArrowRight]].map(([title, sub, Icon]) => <button key={String(title)} type="button" onClick={() => toast.info(String(title) + ' is available from your order/account.')} className="rounded-xl border border-slate-100 bg-slate-50 p-2.5 text-left hover:bg-white"><span className="flex size-8 items-center justify-center rounded-lg bg-white text-primary shadow-sm"><Icon className="size-4" /></span><p className="mt-1.5 text-[10px] font-black">{title}</p><p className="text-[8px] text-slate-400">{sub}</p></button>)}</div></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">10 · Notifications</p><h2 className="text-base font-black">Updates & Support</h2><div className="mt-3 space-y-2">{['Push notifications','SMS updates','WhatsApp updates','Email updates'].map((label, i) => <div key={label} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5"><span className="flex items-center gap-2 text-[10px] font-semibold"><MessageCircle className="size-4 text-primary" />{label}</span><span className={cn('h-4 w-7 rounded-full p-0.5', i === 3 ? 'bg-slate-200' : 'bg-emerald-500')}><span className={cn('block size-3 rounded-full bg-white shadow-sm', i === 3 ? '' : 'ml-3')} /></span></div>)}</div><a href={'https://wa.me/' + STORE_WHATSAPP + '?text=' + encodeURIComponent('Hi Wellcare, I need help with order ' + shortOrderId(confirmed.orderId))} target="_blank" rel="noopener noreferrer" className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-2.5 text-[10px] font-extrabold text-white"><MessageCircle className="size-4" /> Chat with Pharmacist · 24/7</a></section>

              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-5"><p className="text-[9px] font-black uppercase tracking-wider text-primary">11 · Live order tracking</p><h2 className="text-base font-black">Delivery Tracking</h2><div className="relative mt-3 h-36 overflow-hidden rounded-2xl bg-[linear-gradient(135deg,#dff4e8,#eef7ff_50%,#dbeafe)]"><div className="absolute left-[12%] top-[65%] size-4 rounded-full border-2 border-white bg-blue-600 shadow" /><div className="absolute left-[30%] top-[48%] size-3 rounded-full border-2 border-white bg-blue-400" /><div className="absolute left-[52%] top-[35%] size-3 rounded-full border-2 border-white bg-cyan-500" /><div className="absolute right-[13%] top-[20%] flex size-9 items-center justify-center rounded-full bg-emerald-600 text-white shadow-lg"><MapPinned className="size-5" /></div><div className="absolute left-[17%] top-[57%] h-1 w-[60%] -rotate-[25deg] rounded-full bg-blue-500/70" /><div className="absolute bottom-2 left-2 rounded-full bg-white/90 px-2 py-1 text-[8px] font-bold shadow-sm">Your location</div><div className="absolute right-2 top-2 rounded-full bg-emerald-600 px-2 py-1 text-[8px] font-bold text-white">Wellcare Store</div></div><div className="mt-2 flex items-center justify-between rounded-xl bg-slate-50 p-2.5"><span className="flex items-center gap-2 text-[10px] font-bold"><Truck className="size-4 text-blue-600" /> {confirmed.fulfillment === 'delivery' ? 'Out for delivery after dispatch' : 'Pickup journey'}</span><Link to="/track/$orderId" params={{ orderId: confirmed.orderId }} className="text-[9px] font-black text-primary">Open tracker →</Link></div></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-3"><p className="text-[9px] font-black uppercase tracking-wider text-primary">12 · Care journey</p><h2 className="text-base font-black">All Services</h2><div className="mt-3 space-y-2">{[['Consultation','Completed'],['Prescription','Verified'],['Medicines','Out for delivery'],['Lab test','Not added']].map(([a,b],i) => <div key={a} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2"><span className={cn('flex size-6 items-center justify-center rounded-full text-[9px] font-black text-white', i < 3 ? 'bg-emerald-500' : 'bg-slate-300')}>{i < 3 ? '✓' : '4'}</span><div><p className="text-[9px] font-bold">{a}</p><p className="text-[8px] text-slate-400">{b}</p></div></div>)}</div></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">13 · Health plan</p><h2 className="text-base font-black">Health Plan & Membership</h2><div className="mt-3 rounded-xl bg-gradient-to-r from-blue-800 to-cyan-700 p-3 text-white"><p className="text-xs font-black">Wellcare Health Plan</p><p className="mt-1 text-[9px] text-white/70">Unlock consultations, diagnostics and delivery benefits.</p><div className="mt-2 grid grid-cols-2 gap-2 text-[9px]"><span>✓ Member discounts</span><span>✓ Priority support</span><span>✓ Consultation credits</span><span>✓ Delivery benefits</span></div></div><button type="button" onClick={() => toast.info('Health Plan will be available from the membership section.')} className="mt-2 w-full rounded-xl border border-blue-200 py-2 text-[10px] font-extrabold text-blue-700">View Plans & Upgrade</button></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">14 · Documents</p><h2 className="text-base font-black">Invoices & Reports</h2><div className="mt-3 space-y-1.5">{['Invoice','Prescription','Lab Report','Consultation Summary','Payment Receipt'].map((doc) => <button key={doc} type="button" onClick={() => toast.info(String(doc) + ' will be available from the order details.')} className="flex w-full items-center justify-between rounded-xl border border-slate-100 px-3 py-2.5 text-left hover:bg-slate-50"><span className="flex items-center gap-2 text-[10px] font-bold"><FileText className="size-4 text-primary" />{doc}</span><ChevronRight className="size-3.5 text-slate-400" /></button>)}</div></section>
              <section className="rounded-2xl border border-white bg-white p-4 shadow-[0_12px_35px_-22px_rgba(15,23,42,.45)] lg:col-span-4"><p className="text-[9px] font-black uppercase tracking-wider text-primary">15 · Next steps</p><h2 className="text-base font-black">Quick Actions</h2><div className="mt-3 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 p-3 text-white"><p className="text-xs font-black">Your order is on the way!</p><p className="mt-1 text-[9px] text-white/80">Sit back and relax — we’ll keep you updated.</p></div><Link to="/track/$orderId" params={{ orderId: confirmed.orderId }} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 py-2.5 text-[10px] font-extrabold text-white"><PackageCheck className="size-4" /> Track Order</Link><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => toast.info('Reorder will use your saved order details.')} className="rounded-xl bg-slate-50 p-2 text-[9px] font-bold">↻ Reorder</button><button type="button" onClick={() => toast.info('Need help? Chat with our pharmacist on WhatsApp.')} className="rounded-xl bg-slate-50 p-2 text-[9px] font-bold">Need Help?</button></div></section>
              <div className="flex flex-col gap-2 py-2 sm:flex-row sm:items-center sm:justify-center lg:col-span-12"><a href={'https://wa.me/' + STORE_WHATSAPP + '?text=' + encodeURIComponent(buildWhatsAppMessage(confirmed))} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-5 text-xs font-extrabold text-white shadow-lg"><MessageCircle className="size-4" /> WhatsApp Support</a><Link to="/orders" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 text-xs font-extrabold text-slate-700"><PackageCheck className="size-4" /> My Orders</Link><Button variant="outline" className="min-h-11 rounded-2xl bg-white px-5 text-xs font-extrabold" onClick={() => navigate({ to: '/' })}><ShoppingBag className="mr-2 size-4" /> Continue Shopping</Button></div>
            </div>
          </main>
        </div>
      </div>
    )}
  </div>
}
