import { createFileRoute, Link } from '@tanstack/react-router'
import { useMutation, useQuery } from 'convex/react'
import { useConvexAuth } from 'convex/react'
import { useEffect, useState } from 'react'
import { api } from '../../convex/_generated/api'
import { ChevronRight, ClipboardList, Heart, FileText, Shield, UserRound, Save, Loader2, MapPin, Phone, Store, Navigation, MessageCircle, PackageCheck } from 'lucide-react'
import { STORE_LOCATION } from '@/config/store-location'
import { BrandLogo, SiteFooter } from '@/components/brand'

export const Route = createFileRoute('/profile')({ head: () => ({ meta: [{ title: 'My Account — Wellcare Medicose' }] }), component: ProfilePage })
const AVATARS = ['😊','🙂','😎','🥰','🧑‍⚕️','👩‍⚕️','👨‍⚕️','🦊','🐼','🐱','🐶','🌸']
const empty = { name:'', dateOfBirth:'', gender:'', addressLine:'', landmark:'', city:'', state:'', pincode:'', avatarKey:'😊', emergencyContact:'' }
type Fields = typeof empty
function ProfilePage() {
 const { isAuthenticated, isLoading } = useConvexAuth()
 const profile = useQuery(api.profile.getMine, isAuthenticated ? {} : 'skip')
 const save = useMutation(api.profile.updateMine)
 const [form,setForm] = useState<Fields>(empty)
 const [busy,setBusy] = useState(false); const [notice,setNotice] = useState('')
 useEffect(() => { if(profile) setForm({ name:profile.name ?? '', dateOfBirth:profile.dateOfBirth ?? '', gender:profile.gender ?? '', addressLine:profile.addressLine ?? '', landmark:profile.landmark ?? '', city:profile.city ?? '', state:profile.state ?? '', pincode:profile.pincode ?? '', avatarKey:profile.avatarKey ?? '😊', emergencyContact:profile.emergencyContact ?? '' }) }, [profile])
 const change = (key:keyof Fields,value:string) => setForm(old=>({...old,[key]:value}))
 async function submit(e:React.FormEvent) { e.preventDefault(); setBusy(true); setNotice(''); try { const result=await save(form); setNotice(result==='saved'?'Your personal details have been saved.':'Please sign in to save your account.'); } catch(err) { setNotice(err instanceof Error ? err.message : 'Could not save changes. Please try again.') } finally { setBusy(false) } }
 const fieldClass='mt-1.5 w-full rounded-xl border border-border bg-background px-3.5 py-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15'
 const labelClass='text-sm font-medium'
 const mapsUrl=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(STORE_LOCATION.label)}`
 return <div className="relative min-h-screen overflow-x-hidden bg-muted/30"><header className="sticky top-0 z-30 border-b border-border/70 bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><BrandLogo/><Link to="/" className="rounded-full border border-border bg-card px-4 py-2 text-sm font-semibold text-primary">Continue shopping</Link></div></header>
 <main className="mx-auto max-w-3xl px-4 py-7 sm:py-10"><div className="mb-6 rounded-3xl bg-gradient-to-br from-primary via-primary to-teal-700 p-6 text-primary-foreground shadow-lg"><div className="flex items-center gap-4"><div className="flex size-14 items-center justify-center rounded-2xl bg-white/15 text-3xl ring-1 ring-white/25">{form.avatarKey || '😊'}</div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/70">Wellcare Medicose</p><h1 className="mt-1 text-2xl font-bold">My Account</h1><p className="mt-1 text-sm text-white/80">Manage your personal details and delivery information.</p></div></div></div>
 {!isLoading && !isAuthenticated ? <div className="mb-5 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">Please <Link to="/sign-in" className="font-bold underline">sign in</Link> to view and save your private account details.</div> : null}
 <form onSubmit={submit} className="space-y-5">
 <section className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><UserRound/></span><div><h2 className="font-bold">Profile & personal details</h2><p className="text-xs text-muted-foreground">Choose an avatar and tell us about yourself.</p></div></div>
 <label className={labelClass}>Choose your avatar</label><div className="mt-2 grid grid-cols-6 gap-2 sm:grid-cols-12">{AVATARS.map(a=><button type="button" key={a} aria-label={`Choose avatar ${a}`} onClick={()=>change('avatarKey',a)} className={`flex aspect-square items-center justify-center rounded-xl border text-2xl transition hover:-translate-y-0.5 hover:border-primary ${form.avatarKey===a?'border-primary bg-primary/10 ring-2 ring-primary/20':'border-border bg-muted/40'}`}>{a}</button>)}</div><p className="mt-2 text-xs text-muted-foreground">You can select a profile avatar here. Profile photo upload can be added with secure image storage.</p>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={labelClass}>Full name</label><input className={fieldClass} autoComplete="name" value={form.name} onChange={e=>change('name',e.target.value)} placeholder="Your full name" required/></div><div><label className={labelClass}>Date of birth</label><input className={fieldClass} type="date" value={form.dateOfBirth} onChange={e=>change('dateOfBirth',e.target.value)}/></div><div><label className={labelClass}>Gender (optional)</label><select className={fieldClass} value={form.gender} onChange={e=>change('gender',e.target.value)}><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Other</option></select></div><div><label className={labelClass}>Email / Gmail</label><input className={fieldClass+' opacity-70'} value={profile?.email ?? ''} readOnly placeholder="Email from your sign-in account"/><p className="mt-1 text-xs text-muted-foreground">Managed by your verified sign-in provider.</p></div><div><label className={labelClass}>Phone number</label><input className={fieldClass+' opacity-70'} value={profile?.phone ?? ''} readOnly placeholder="Phone from your sign-in account"/><p className="mt-1 text-xs text-muted-foreground">Managed by your sign-in provider.</p></div></div></section>
 <section className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><MapPin/></span><div><h2 className="font-bold">Delivery address</h2><p className="text-xs text-muted-foreground">Add details to make deliveries easier.</p></div></div><div className="space-y-4"><div><label className={labelClass}>House / Flat, street, area</label><textarea className={fieldClass} rows={2} autoComplete="street-address" value={form.addressLine} onChange={e=>change('addressLine',e.target.value)} placeholder="House no., street and locality"/></div><div><label className={labelClass}>Landmark (optional)</label><input className={fieldClass} value={form.landmark} onChange={e=>change('landmark',e.target.value)} placeholder="Nearby landmark"/></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={labelClass}>City</label><input className={fieldClass} autoComplete="address-level2" value={form.city} onChange={e=>change('city',e.target.value)} placeholder="City"/></div><div><label className={labelClass}>State</label><input className={fieldClass} autoComplete="address-level1" value={form.state} onChange={e=>change('state',e.target.value)} placeholder="State"/></div><div><label className={labelClass}>PIN code</label><input className={fieldClass} inputMode="numeric" maxLength={6} autoComplete="postal-code" value={form.pincode} onChange={e=>change('pincode',e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-digit PIN code"/></div><div><label className={labelClass}>Emergency contact (optional)</label><input className={fieldClass} type="tel" value={form.emergencyContact} onChange={e=>change('emergencyContact',e.target.value)} placeholder="Alternate contact number"/></div></div></div></section>
 {notice && <p role="status" className={`rounded-xl p-3 text-sm ${notice.includes('saved')?'bg-emerald-50 text-emerald-800':'bg-rose-50 text-rose-800'}`}>{notice}</p>}
 <button disabled={!isAuthenticated||busy} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-4 font-semibold text-primary-foreground shadow-md transition hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-50">{busy?<Loader2 className="size-5 animate-spin"/>:<Save className="size-5"/>}{busy?'Saving details…':'Save personal details'}</button>
 </form>
 <section className="mt-6 rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-6">
<div className="mb-4 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Shield/></span><div><h2 className="font-bold">Store Team</h2><p className="text-xs text-muted-foreground">Authorized access for Wellcare Medicose staff.</p></div></div>
<div className="grid gap-3 sm:grid-cols-2">
<Link to="/admin" className="flex items-center gap-3 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm font-semibold text-primary transition hover:border-primary/40 hover:bg-primary/10"><Shield className="size-5"/><span>Admin Panel<span className="block text-xs font-normal text-muted-foreground">Manage medicines, orders & store</span></span><ChevronRight className="ml-auto size-4"/></Link>
<Link to="/staff" className="flex items-center gap-3 rounded-2xl border border-border bg-muted/30 p-4 text-sm font-semibold transition hover:border-primary/40"><UserRound className="size-5 text-primary"/><span>Staff Login<span className="block text-xs font-normal text-muted-foreground">Order & store operations</span></span><ChevronRight className="ml-auto size-4"/></Link>
</div></section>
<section className="mt-4 rounded-3xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm"><div className="flex items-start gap-3"><MessageCircle className="mt-0.5 size-6 shrink-0 text-emerald-600"/><div><h2 className="font-bold text-emerald-900">Help & Support</h2><p className="mt-1 text-sm text-emerald-800">Need help with an order, medicine or delivery? Chat directly with the Wellcare Medicose admin on WhatsApp.</p><a href="https://wa.me/917088252556?text=Hello%20Wellcare%20Medicose%2C%20I%20need%20help%20with%20my%20order." target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#25D366] px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><MessageCircle className="size-4"/>Chat with Admin on WhatsApp</a></div></div></section>

 <div className="mt-6 grid gap-3 sm:grid-cols-2">{[{to:'/orders',label:'My Orders',icon:ClipboardList},{to:'/wishlist',label:'Wishlist',icon:Heart},{to:'/returns',label:'Returns & Refunds',icon:FileText},{to:'/privacy',label:'Privacy Policy',icon:Shield}].map(({to,label,icon:Icon})=><Link key={to} to={to} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 text-sm font-semibold transition hover:border-primary/40"><Icon className="size-5 text-primary"/>{label}<ChevronRight className="ml-auto size-4 text-muted-foreground"/></Link>)}</div>
 <section className="mt-6 rounded-3xl border border-border bg-card p-5"><div className="flex items-center gap-3"><Store className="size-5 text-primary"/><h2 className="font-bold">Store information</h2></div><p className="mt-3 text-sm text-muted-foreground">{STORE_LOCATION.label}</p><a href={mapsUrl} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex items-center gap-2 text-sm font-semibold text-primary"><Navigation className="size-4"/>Get directions</a><p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><Phone className="size-4"/>+91 70882 52556</p><a className="mt-2 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700" href="https://wa.me/917088252556" target="_blank" rel="noopener noreferrer"><MessageCircle className="size-4"/>WhatsApp support</a></section>
 <div className="mt-4 flex gap-3 rounded-2xl bg-emerald-50 p-4 text-xs leading-5 text-emerald-900"><PackageCheck className="size-5 shrink-0"/>Prescription medicines may require a valid prescription. Only provide personal details needed for your account and delivery.</div></main><SiteFooter/></div>
}
