import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useAuthActions } from '@convex-dev/auth/react'
import { useState } from 'react'
import { Loader2, Mail, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export const Route = createFileRoute('/staff-login')({ head:()=>({meta:[{title:'Staff sign in — Wellcare Medicose'}]}), component:StaffLoginPage })

function StaffLoginPage(){
 const {signIn}=useAuthActions(); const navigate=useNavigate()
 const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [step,setStep]=useState<'email'|'code'>('email'); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 async function requestCode(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');try{const d=new FormData();d.set('email',email.trim().toLowerCase());await signIn('resend-otp',d);setStep('code')}catch(err){setError(err instanceof Error?err.message:'Could not send the verification code.')}finally{setLoading(false)}}
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');try{const d=new FormData();d.set('email',email.trim().toLowerCase());d.set('code',code);await signIn('resend-otp',d);await navigate({to:'/staff'})}catch(err){setError(err instanceof Error?err.message:'Verification failed.')}finally{setLoading(false)}}
 return <main className="flex min-h-screen items-center justify-center bg-slate-950 px-4 py-10"><section className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.06] p-7 text-white shadow-2xl sm:p-9"><div className="mx-auto mb-5 flex size-14 items-center justify-center rounded-2xl bg-emerald-400/15 text-emerald-300"><ShieldCheck className="size-7"/></div><h1 className="text-center text-2xl font-bold">Staff sign in</h1><p className="mt-2 text-center text-sm text-slate-300">Wellcare Medicose · Authorized staff only</p>{step==='email'?<form onSubmit={requestCode} className="mt-7 space-y-4"><label className="block text-sm">Registered staff email</label><Input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter staff email" className="h-12 bg-white text-slate-900"/><Button className="h-12 w-full bg-emerald-500 hover:bg-emerald-600" disabled={loading}>{loading?<Loader2 className="mr-2 size-4 animate-spin"/>:<Mail className="mr-2 size-4"/>}{loading?'Sending code…':'Send sign-in code'}</Button></form>:<form onSubmit={verify} className="mt-7 space-y-4"><p className="text-sm text-slate-300">Enter the code sent to <b className="text-white">{email}</b>.</p><Input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-digit code" className="h-12 bg-white text-center text-lg tracking-[0.4em] text-slate-900"/><Button className="h-12 w-full bg-emerald-500 hover:bg-emerald-600" disabled={loading}>{loading?'Verifying…':'Verify and enter'}</Button><button type="button" onClick={()=>{setStep('email');setCode('')}} className="w-full text-sm underline">Use a different email</button></form>}{error&&<p role="alert" className="mt-4 rounded-xl bg-red-500/15 p-3 text-sm text-red-200">{error}</p>}</section></main>
}
