import { useNavigate } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { ShoppingCart, Tag, Trash2, Plus, Minus, ArrowRight, ShieldCheck, PackageCheck, ClipboardList, Truck, CreditCard, MapPin, Sparkles, ChevronRight } from 'lucide-react'
import { useCart } from '@/hooks/use-cart'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetFooter } from '@/components/ui/sheet'

export const OPEN_CART_EVENT = 'wellcare-open-cart'
const COUPON_KEY = 'wellcare-coupon'
function formatINR(n: number) { return `₹${n.toFixed(2)}` }

export function CartDrawer() {
  const { lines, total, mrpTotal, changeQty } = useCart()
  const navigate = useNavigate()
  const [open, setOpen] = useState(false)
  const [couponCode, setCouponCode] = useState('')
  useEffect(() => {
    function onOpen() { setOpen(true) }
    window.addEventListener(OPEN_CART_EVENT, onOpen)
    return () => window.removeEventListener(OPEN_CART_EVENT, onOpen)
  }, [])
  useEffect(() => {
    try { const saved = window.localStorage.getItem(COUPON_KEY); if (saved) setCouponCode(saved) } catch { /* ignore */ }
  }, [open])
  const discount = Math.max(0, mrpTotal - total)
  const deliveryChargeEstimate = total >= 499 || total === 0 ? 0 : 40
  function applyCoupon() {
    const code = couponCode.trim().toUpperCase()
    if (!code) return
    try { window.localStorage.setItem(COUPON_KEY, code) } catch { /* ignore */ }
    toast.success(`Coupon ${code} will be applied at checkout`)
  }
  function handleContinue() { setOpen(false); navigate({ to: '/checkout' }) }

  return (
    <Sheet open={open} onOpenChange={setOpen}>
      <SheetContent className="flex w-full flex-col gap-0 overflow-hidden border-l border-white/30 bg-slate-950/10 p-0 shadow-[-20px_0_60px_-30px_rgba(15,118,110,0.55)] backdrop-blur-2xl sm:max-w-3xl">
        <SheetHeader className="relative overflow-hidden border-b border-white/50 bg-gradient-to-r from-[#063b42]/95 via-[#087f7b]/95 to-[#0b5ea8]/95 px-5 py-4 text-left text-white shadow-lg sm:px-6">
          <div className="absolute -right-16 -top-20 size-48 rounded-full bg-cyan-300/20 blur-3xl" /><div className="absolute -left-10 -bottom-16 size-40 rounded-full bg-emerald-300/15 blur-3xl" />
          <div className="relative flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl border border-white/25 bg-white/15 shadow-inner backdrop-blur-md"><ShoppingCart className="size-5" /></span><div className="min-w-0"><SheetTitle className="text-xl font-black tracking-tight text-white">Add to Cart</SheetTitle><p className="mt-0.5 truncate text-xs text-cyan-50/85">{lines.length ? lines.length + ' items ready · Review before checkout' : 'Your Wellcare healthcare basket'}</p></div></div>{lines.length > 0 && <div className="hidden items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-2 text-xs font-bold backdrop-blur-md sm:flex"><Sparkles className="size-3.5 text-emerald-200" /> Smart cart</div>}</div>
          {lines.length > 0 && <div className="relative mt-5 grid grid-cols-4 gap-1.5">{[['Cart', ShoppingCart], ['Prescription', ClipboardList], ['Fulfilment', Truck], ['Checkout', CreditCard]].map(([label, Icon], i) => { const StepIcon = Icon as typeof ShoppingCart; return <div key={String(label)} className="relative flex items-center gap-2 rounded-xl border border-white/10 bg-white/10 px-2.5 py-2 backdrop-blur-md"><span className={i === 0 ? 'flex size-7 shrink-0 items-center justify-center rounded-full bg-white text-[#087f7b]' : 'flex size-7 shrink-0 items-center justify-center rounded-full bg-white/15 text-white'}><StepIcon className="size-3.5" /></span><span className="hidden text-[10px] font-bold sm:block">{String(label)}</span>{i < 3 && <ChevronRight className="absolute -right-2.5 z-10 hidden size-4 text-white/50 sm:block" />}</div> })}</div>}
        </SheetHeader>
        <div className="flex-1 overflow-y-auto bg-[radial-gradient(circle_at_top_left,rgba(20,184,166,0.12),transparent_34%),linear-gradient(145deg,#f8fcfc_0%,#eef7fb_48%,#f8fafc_100%)] px-3 py-4 sm:px-5">
          {lines.length === 0 ? <div className="flex min-h-[55vh] flex-col items-center justify-center rounded-3xl border border-white/70 bg-white/65 px-5 text-center shadow-[0_20px_60px_-40px_rgba(15,118,110,0.5)] backdrop-blur-xl"><span className="mb-4 flex size-20 items-center justify-center rounded-full bg-gradient-to-br from-emerald-100 to-cyan-100 text-primary shadow-inner"><ShoppingCart className="size-9" /></span><h3 className="text-xl font-black text-slate-900">Your cart is empty</h3><p className="mt-2 max-w-[280px] text-sm leading-6 text-slate-500">Find medicines and everyday healthcare essentials for you and your family.</p><Button className="mt-5 rounded-xl bg-gradient-to-r from-primary to-brand-teal px-7 font-bold shadow-lg" onClick={() => { setOpen(false); navigate({ to: '/' }) }}>Continue shopping <ArrowRight className="ml-2 size-4" /></Button><div className="mt-6 flex items-center gap-2 text-xs font-medium text-slate-500"><ShieldCheck className="size-4 text-primary" /> Secure shopping at Wellcare Medicose</div></div> :
            <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-3">
              <div className="flex items-center justify-between px-1"><div><p className="text-sm font-black text-slate-900">Your Items <span className="text-primary">({lines.length})</span></p><p className="text-[11px] text-slate-500">Adjust quantity or remove anything you don't need.</p></div><button type="button" className="rounded-lg bg-white/70 px-2.5 py-1.5 text-[11px] font-bold text-slate-500 shadow-sm hover:text-destructive" onClick={() => lines.forEach(line => changeQty(line.medicineId, -line.quantity))}>Clear Cart</button></div>
              <div className="space-y-2.5">{lines.map((line, index) => <article key={line.medicineId} className="group rounded-2xl border border-white/80 bg-white/82 p-3.5 shadow-[0_8px_24px_-18px_rgba(15,23,42,0.45)] backdrop-blur-md transition-all hover:-translate-y-0.5 hover:shadow-[0_14px_30px_-20px_rgba(15,118,110,0.45)]"><div className="flex gap-3"><div className="flex size-16 shrink-0 items-center justify-center rounded-2xl border border-cyan-100 bg-gradient-to-br from-cyan-50 via-white to-emerald-50 text-primary shadow-inner"><PackageCheck className="size-7" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="line-clamp-2 text-sm font-extrabold leading-5 text-slate-800">{line.name}</p><p className="mt-0.5 text-[10px] font-medium text-slate-400">Healthcare product · Item {index + 1}</p></div><button type="button" aria-label={'Remove ' + line.name} className="rounded-lg p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={() => changeQty(line.medicineId, -line.quantity)}><Trash2 className="size-4" /></button></div><div className="mt-2 flex items-center justify-between gap-2"><div className="flex items-baseline gap-2"><span className="text-base font-black text-[#087f7b]">{formatINR(line.price)}</span>{line.mrpPrice && line.mrpPrice > line.price && <span className="text-[11px] text-slate-400 line-through">{formatINR(line.mrpPrice)}</span>}</div><div className="inline-flex items-center rounded-xl border border-slate-200 bg-slate-50 p-1 shadow-inner"><Button size="icon" variant="ghost" className="size-7 rounded-lg" aria-label={'Decrease quantity of ' + line.name} onClick={() => changeQty(line.medicineId, -1)}><Minus className="size-3.5" /></Button><span className="w-7 text-center text-xs font-black tabular-nums">{line.quantity}</span><Button size="icon" variant="ghost" className="size-7 rounded-lg" aria-label={'Increase quantity of ' + line.name} onClick={() => changeQty(line.medicineId, 1)}><Plus className="size-3.5" /></Button></div></div></div></div></article>)}</div>
              <div className="rounded-2xl border border-emerald-200/70 bg-gradient-to-r from-emerald-50/90 to-cyan-50/90 p-3.5 shadow-sm backdrop-blur-md"><div className="flex items-center gap-2 text-sm font-black text-emerald-900"><Truck className="size-4" /> Fulfilment options</div><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3"><div className="rounded-xl border border-emerald-300 bg-white/75 p-2.5"><p className="text-xs font-bold text-slate-800">Home Delivery</p><p className="mt-0.5 text-[10px] text-emerald-700">Fast & convenient</p></div><div className="rounded-xl border border-cyan-200 bg-white/65 p-2.5"><p className="text-xs font-bold text-slate-800">Store Pickup</p><p className="mt-0.5 text-[10px] text-cyan-700">Ready at store</p></div><div className="hidden rounded-xl border border-slate-200 bg-white/65 p-2.5 sm:block"><p className="text-xs font-bold text-slate-800">Schedule</p><p className="mt-0.5 text-[10px] text-slate-500">Choose a time</p></div></div></div>
              <div className="rounded-2xl border border-white/80 bg-white/70 p-3.5 backdrop-blur-md"><div className="mb-2 flex items-center gap-2 text-sm font-black text-slate-800"><Tag className="size-4 text-primary" /> Have a coupon?</div><div className="flex gap-2"><Input value={couponCode} onChange={e => setCouponCode(e.target.value)} placeholder="Enter coupon code" className="h-10 min-w-0 rounded-xl border-slate-200 bg-white/80 text-sm uppercase" /><Button variant="outline" className="h-10 rounded-xl border-primary/30 px-4 font-bold text-primary" onClick={applyCoupon}>Apply</Button></div></div>
            </div><aside className="lg:sticky lg:top-2 lg:self-start"><div className="overflow-hidden rounded-3xl border border-white/80 bg-white/82 shadow-[0_18px_45px_-28px_rgba(15,118,110,0.6)] backdrop-blur-xl"><div className="bg-gradient-to-r from-[#075e63] to-[#0b6fae] px-4 py-3 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-100">Order Summary</p><p className="mt-0.5 text-lg font-black">{lines.length} items · Ready to checkout</p></div><div className="space-y-2.5 p-4 text-sm"><div className="flex justify-between text-slate-500"><span>MRP total</span><span>{formatINR(mrpTotal)}</span></div>{discount > 0 && <div className="flex justify-between font-bold text-emerald-600"><span>You save</span><span>−{formatINR(discount)}</span></div>}<div className="flex justify-between text-slate-500"><span>Delivery</span><span className={deliveryChargeEstimate === 0 ? 'font-bold text-emerald-600' : ''}>{deliveryChargeEstimate === 0 ? 'FREE' : formatINR(deliveryChargeEstimate)}</span></div><Separator /><div className="flex items-end justify-between gap-2"><span className="font-black text-slate-800">Total payable</span><span className="text-2xl font-black text-[#087f7b]">{formatINR(total + deliveryChargeEstimate)}</span></div>{discount > 0 && <div className="rounded-xl bg-emerald-50 px-3 py-2 text-center text-[11px] font-bold text-emerald-700">🎉 You saved {formatINR(discount)} on this cart</div>}</div><div className="border-t border-slate-100 bg-slate-50/70 p-3"><Button className="h-12 w-full rounded-xl bg-gradient-to-r from-[#087f7b] to-[#0b6fae] text-sm font-black text-white shadow-[0_12px_26px_-12px_rgba(8,127,123,0.8)] hover:brightness-105" onClick={handleContinue} data-testid="continue-checkout">Proceed to checkout <ArrowRight className="ml-2 size-4" /></Button><div className="mt-2 flex items-center justify-center gap-2 text-[10px] font-semibold text-slate-500"><ShieldCheck className="size-3.5 text-emerald-600" /> Secure payment <span>•</span><MapPin className="size-3.5 text-cyan-600" /> Delivery & pickup available</div></div></div></aside></div>}
        </div>
        {lines.length > 0 && <SheetFooter className="border-t border-white/60 bg-white/90 px-3 py-3 shadow-[0_-12px_30px_-24px_rgba(15,118,110,0.7)] backdrop-blur-xl lg:hidden"><Button className="h-12 w-full rounded-xl bg-gradient-to-r from-[#087f7b] to-[#0b6fae] text-sm font-black text-white shadow-lg" onClick={handleContinue} data-testid="continue-checkout">Proceed to checkout <ArrowRight className="ml-2 size-4" /></Button></SheetFooter>}      </SheetContent>
    </Sheet>
  )
}
