import { Link } from '@tanstack/react-router'
import { ArrowRight, Bell, Check, CheckCircle2, Crown, Download, FileText, FlaskConical, Heart, MessageCircle, PackageCheck, Phone, Pill, RefreshCw, RotateCcw, ShoppingBag, Stethoscope, Store, Truck } from 'lucide-react'
import type { ReactNode } from 'react'
import type { CartLine } from '@/hooks/use-cart'
import { BrandLogo } from '@/components/brand'
import { STORE_LOCATION } from '@/config/store-location'
import { Button } from '@/components/ui/button'

type Order = { orderId:string; total:number; customerName:string; fulfillment:'pickup'|'delivery'; deliveryAddress?:string; items:CartLine[] }
const money=(n:number)=>`₹${n.toFixed(2)}`
const oid=(s:string)=>s.slice(-8).toUpperCase()

export function OrderConfirmationScreen({order,whatsappUrl,onContinue}:{order:Order;whatsappUrl:string;onContinue:()=>void}){
 const delivery=order.fulfillment==='delivery'
 const steps=delivery?['Order Confirmed','Pharmacy Preparing','Packed','Out for Delivery','Delivered']:['Order Confirmed','Preparing','Ready for Pickup','Collected']
 return <div className="fixed inset-0 z-[100] h-[100dvh] overflow-hidden bg-gradient-to-b from-[#effaf7] via-white to-[#f3f8ff] text-slate-900"><div className="mx-auto flex h-full max-w-7xl flex-col">
  <header className="shrink-0 border-b border-white bg-white/80 px-4 py-3 backdrop-blur-2xl sm:px-6"><div className="flex items-center justify-between"><BrandLogo/><span className="rounded-full border border-emerald-200 bg-white px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-emerald-700">Order confirmed</span></div></header>
  <main className="min-h-0 flex-1 overflow-y-auto px-3 pb-6 pt-3 sm:px-5 lg:px-7">
   <div className="grid gap-3 lg:grid-cols-3">
    <Panel n="1" t="Order Confirmed — Your Healthcare Journey"><div className="flex items-center gap-3"><span className="flex size-14 items-center justify-center rounded-full bg-emerald-50"><CheckCircle2 className="size-8 text-emerald-600"/></span><div><h1 className="text-2xl font-black">Order confirmed 🎉</h1><p className="text-xs text-slate-500">Your order has been successfully placed.</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><Stat a="Order ID" b={`WC${oid(order.orderId)}`}/><Stat a="Total paid" b={money(order.total)}/></div></Panel>
    <Panel n="2" t="Your Healthcare Journey"><div className="space-y-2">{steps.map((x,i)=><div className="flex items-center gap-2" key={x}><span className={`flex size-7 items-center justify-center rounded-full ${i<2?'bg-emerald-600 text-white':'border-2 border-slate-200 text-slate-300'}`}>{i<2?<Check className="size-4"/>:<span className="size-1.5 rounded-full bg-current"/>}</span><span className={`text-xs font-semibold ${i===1?'text-emerald-700':'text-slate-600'}`}>{x}</span></div>)}</div></Panel>
    <Panel n="3" t="Order Details"><Row a="Fulfilment" b={delivery?'Express Delivery':'Store Pickup'}/><Row a="Customer" b={order.customerName}/><div className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs font-black text-emerald-800">{delivery?'ETA: Today · 30–45 min':'Ready soon · we’ll notify you'}</div></Panel>
   </div>
   <div className="mt-3 grid gap-3 lg:grid-cols-12">
    <Panel n="4" t="Items in Your Order" c="lg:col-span-4">{order.items.slice(0,4).map(x=><div className="mb-2 flex items-center gap-2 rounded-xl border bg-white/70 p-2" key={x.medicineId}><span className="flex size-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Pill className="size-5"/></span><span className="min-w-0 flex-1 truncate text-xs font-bold">{x.name}<small className="block text-[9px] font-normal text-slate-400">Qty: {x.quantity}</small></span><b className="text-xs">{money(x.price*x.quantity)}</b></div>)}<p className="text-[10px] text-slate-400">{order.items.reduce((a,x)=>a+x.quantity,0)} items total</p></Panel>
    <Panel n="5" t="Price Breakdown" c="lg:col-span-4"><Row a="Items total" b={money(order.total)}/><Row a="Delivery fee" b="FREE"/><Row a="Taxes & processing" b="Included"/><div className="mt-3 flex justify-between rounded-xl bg-emerald-50 p-3 text-sm font-black text-emerald-800"><span>Total Paid</span><span>{money(order.total)}</span></div></Panel>
    <Panel n="6" t="Prescription & Consultation" c="lg:col-span-4"><div className="rounded-xl bg-gradient-to-r from-blue-700 to-indigo-600 p-3 text-white"><CheckCircle2 className="inline size-5"/><b className="ml-2 text-sm">Prescription Verified</b><p className="mt-1 text-[10px] text-white/75">Your order is cleared for processing.</p></div><Tile I={Stethoscope} t="Chat with pharmacist" s="Medicine guidance"/></Panel>
    <Panel n="7" t="Lab Test & Home Sample Collection" c="lg:col-span-4"><div className="rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-500 p-3 text-white"><FlaskConical className="inline"/><b className="ml-2 text-sm">Home sample collection</b><p className="mt-1 text-[10px]">Book CBC and health packages.</p></div><button className="mt-2 w-full rounded-xl border py-2 text-xs font-bold text-primary">Explore diagnostics</button></Panel>
    <Panel n="8" t="Store Pickup Information" c="lg:col-span-4"><div className="rounded-xl bg-emerald-600 p-3 text-white"><Store className="inline"/><b className="ml-2 text-sm">{delivery?'Store support':'Ready for Pickup'}</b><p className="mt-1 text-[10px]">{STORE_LOCATION.label}</p>{!delivery&&<p className="mt-2 rounded-lg bg-white/15 p-2 text-xs font-black">Pickup code: 4827</p>}</div></Panel>
    <Panel n="9" t="Additional Options" c="lg:col-span-4"><div className="grid grid-cols-2 gap-2"><Tile I={RotateCcw} t="Reschedule" s="Change timing"/><Tile I={Heart} t="Wishlist" s="Save later"/><Tile I={Bell} t="Refill reminder" s="Never miss dose"/><Tile I={RefreshCw} t="Buy again" s="Repeat order"/></div></Panel>
    <Panel n="10" t="Notifications & Updates" c="lg:col-span-4">{['Push notifications','SMS updates','WhatsApp updates','Email receipts'].map((x,i)=><div className="flex justify-between border-b py-2 text-xs" key={x}><span><Bell className="mr-2 inline size-3.5 text-primary"/>{x}</span><b className={i<3?'text-emerald-600':'text-slate-400'}>{i<3?'ON':'OFF'}</b></div>)}</Panel>
    {delivery&&<Panel n="11" t="Live Order Tracking" c="lg:col-span-5"><div className="relative h-40 overflow-hidden rounded-xl bg-gradient-to-br from-sky-100 via-emerald-50 to-blue-100"><span className="absolute left-8 top-8 size-3 rounded-full bg-blue-600 ring-4 ring-blue-100"/><span className="absolute right-8 bottom-7 size-4 rounded-full bg-emerald-600 ring-4 ring-emerald-100"/><div className="absolute left-10 top-10 h-1 w-3/4 rotate-12 bg-blue-500/70"/><span className="absolute right-2 top-2 rounded-full bg-emerald-600 px-2 py-1 text-[9px] font-bold text-white">● LIVE</span><span className="absolute bottom-2 left-2 rounded-lg bg-white/90 px-2 py-1 text-[10px] font-bold">🚚 Rider assigned · ETA 30–45 min</span></div><Button asChild className="mt-2 w-full rounded-xl"><Link to="/track/$orderId" params={{orderId:order.orderId}}><PackageCheck className="mr-2 size-4"/>Track your order</Link></Button></Panel>}
    <Panel n="12" t="My Care Journey" c={delivery?'lg:col-span-4':'lg:col-span-6'}>{[['Consultation','Completed',Stethoscope],['Prescription','Verified',FileText],['Medicines',delivery?'Out for delivery':'Ready for pickup',Pill],['Lab test','Explore collection',FlaskConical]].map(([a,b,I])=><div className="flex items-center gap-2 border-b py-2" key={a as string}><I className="size-4 text-emerald-600"/><span className="flex-1"><b className="block text-xs">{a as string}</b><small className="text-[9px] text-slate-400">{b as string}</small></span><ArrowRight className="size-3 text-slate-300"/></div>)}</Panel>
    <Panel n="13" t="Health Plan & Membership" c={delivery?'lg:col-span-3':'lg:col-span-6'}><div className="rounded-xl bg-gradient-to-br from-slate-900 to-blue-900 p-4 text-white"><Crown className="text-amber-300"/><b className="ml-2 text-sm">Wellcare Health Plan</b><p className="mt-2 text-[10px] text-white/70">Consultations, diagnostics and member benefits.</p><button className="mt-3 w-full rounded-lg bg-white/15 py-2 text-[10px] font-bold">View Plans & Upgrade</button></div></Panel>
    <Panel n="14" t="Documents & Invoice" c="lg:col-span-4">{['Invoice','Prescription','Lab Report','Payment Receipt'].map(x=><button className="flex w-full items-center gap-2 border-b py-2 text-left" key={x}><FileText className="size-4 text-primary"/><span className="flex-1 text-xs font-bold">{x}<small className="block text-[9px] font-normal text-slate-400">View / Download</small></span><Download className="size-3 text-slate-400"/></button>)}</Panel>
    <Panel n="15" t="Next Steps & Quick Actions" c="lg:col-span-4"><p className="rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">💚 Your order is on the way! Sit back and relax.</p><Link to="/track/$orderId" params={{orderId:order.orderId}} className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-primary px-3 py-2.5 text-xs font-bold text-white"><PackageCheck className="size-4"/>Track Order</Link><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="mt-2 flex items-center justify-center gap-2 rounded-xl border border-emerald-200 px-3 py-2.5 text-xs font-bold text-emerald-700"><MessageCircle className="size-4"/>Contact Support</a></Panel>
    <Panel n="Help" t="Need Help?" c="lg:col-span-4"><div className="grid grid-cols-2 gap-2"><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="rounded-xl bg-cyan-50 p-3 text-center"><MessageCircle className="mx-auto text-cyan-700"/><b className="mt-1 block text-[10px]">Chat with Pharmacist</b></a><a href="tel:+917088252556" className="rounded-xl bg-emerald-50 p-3 text-center"><Phone className="mx-auto text-emerald-700"/><b className="mt-1 block text-[10px]">Contact Support</b></a></div></Panel>
   </div>
   <div className="sticky bottom-0 z-20 mt-3 flex flex-col gap-2 rounded-2xl border bg-white/90 p-2 shadow-xl backdrop-blur-2xl sm:flex-row"><Button onClick={onContinue} variant="ghost" className="order-2 sm:order-1"><ShoppingBag className="mr-2 size-4"/>Continue shopping</Button><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="order-3 inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-emerald-200 px-4 text-sm font-bold text-emerald-700 sm:order-2"><MessageCircle className="size-4"/>WhatsApp</a><Link to="/track/$orderId" params={{orderId:order.orderId}} className="order-1 inline-flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-700 to-cyan-600 px-5 text-sm font-black text-white sm:order-3"><PackageCheck className="size-5"/>Track your order<ArrowRight className="size-4"/></Link></div>
  </main></div></div>
}
function Panel({n,t,children,c=''}:{n:string;t:string;children:ReactNode;c?:string}){return <section className={`rounded-[1.3rem] border border-white/90 bg-white/70 p-4 shadow-sm backdrop-blur-xl ${c}`}><div className="mb-3 flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-full bg-slate-900 text-[10px] font-black text-white">{n}</span><h2 className="text-sm font-black">{t}</h2></div>{children}</section>}
function Stat({a,b}:{a:string;b:string}){return <div className="rounded-xl bg-slate-50 p-2.5"><small className="block text-[9px] font-bold uppercase text-slate-400">{a}</small><b className="mt-1 block text-xs">{b}</b></div>}
function Row({a,b}:{a:string;b:string}){return <div className="flex justify-between gap-3 text-xs"><span className="text-slate-400">{a}</span><b>{b}</b></div>}
function Tile({I,t,s}:{I:(p:{className?:string})=>ReactNode;t:string;s:string}){return <div className="rounded-xl border bg-white/70 p-2.5"><I className="size-5 text-primary"/><b className="mt-1 block text-[10px]">{t}</b><small className="text-[9px] text-slate-400">{s}</small></div>}
