/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as MedicineIdRouteImport } from './routes/medicine.$id'
import { Route as AuthGooglePopupRouteImport } from './routes/auth/google/popup'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineIdRoute = MedicineIdRouteImport.update({
  id: '/medicine/$id',
  path: '/medicine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGooglePopupRoute = AuthGooglePopupRouteImport.update({
  id: '/auth/google/popup',
  path: '/auth/google/popup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/wishlist': typeof WishlistRoute
  '/medicine/$id': typeof MedicineIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/popup': typeof AuthGooglePopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/wishlist': typeof WishlistRoute
  '/medicine/$id': typeof MedicineIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/popup': typeof AuthGooglePopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/wishlist': typeof WishlistRoute
  '/medicine/$id': typeof MedicineIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/popup': typeof AuthGooglePopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/returns'
    | '/sign-in'
    | '/staff'
    | '/staff-login'
    | '/wishlist'
    | '/medicine/$id'
    | '/track/$orderId'
    | '/auth/google/callback'
    | '/auth/google/popup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/returns'
    | '/sign-in'
    | '/staff'
    | '/staff-login'
    | '/wishlist'
    | '/medicine/$id'
    | '/track/$orderId'
    | '/auth/google/callback'
    | '/auth/google/popup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/returns'
    | '/sign-in'
    | '/staff'
    | '/staff-login'
    | '/wishlist'
    | '/medicine/$id'
    | '/track/$orderId'
    | '/auth/google/callback'
    | '/auth/google/popup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReturnsRoute: typeof ReturnsRoute
  SignInRoute: typeof SignInRoute
  StaffRoute: typeof StaffRoute
  StaffLoginRoute: typeof StaffLoginRoute
  WishlistRoute: typeof WishlistRoute
  MedicineIdRoute: typeof MedicineIdRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGooglePopupRoute: typeof AuthGooglePopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/$id': {
      id: '/medicine/$id'
      path: '/medicine/$id'
      fullPath: '/medicine/$id'
      preLoaderRoute: typeof MedicineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/popup': {
      id: '/auth/google/popup'
      path: '/auth/google/popup'
      fullPath: '/auth/google/popup'
      preLoaderRoute: typeof AuthGooglePopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReturnsRoute: ReturnsRoute,
  SignInRoute: SignInRoute,
  StaffRoute: StaffRoute,
  StaffLoginRoute: StaffLoginRoute,
  WishlistRoute: WishlistRoute,
  MedicineIdRoute: MedicineIdRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGooglePopupRoute: AuthGooglePopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
